#ifndef _IswArgMacros_h
#define _IswArgMacros_h

#include <ISW/Intrinsic.h>
#include <ISW/StringDefs.h>
#include <ISW/Shell.h>
#include <ISW/Form.h>

#define ISW_ARG(ab, name, v) IswArgBuilderAdd((ab), (name), (IswArgVal)(v))

/* Core (StringDefs.h) */
#define IswArgAccelerators(ab, v)               ISW_ARG((ab), IswNaccelerators, (v))
#define IswArgAllowHoriz(ab, v)                 ISW_ARG((ab), IswNallowHoriz, (v))
#define IswArgAllowVert(ab, v)                  ISW_ARG((ab), IswNallowVert, (v))
#define IswArgAncestorSensitive(ab, v)          ISW_ARG((ab), IswNancestorSensitive, (v))
#define IswArgBackground(ab, v)                 ISW_ARG((ab), IswNbackground, (v))
#define IswArgBackgroundPixmap(ab, v)           ISW_ARG((ab), IswNbackgroundPixmap, (v))
#define IswArgBitmap(ab, v)                     ISW_ARG((ab), IswNbitmap, (v))
#define IswArgBorder(ab, v)                     ISW_ARG((ab), IswNborder, (v))
#define IswArgBorderColor(ab, v)                ISW_ARG((ab), IswNborderColor, (v))
#define IswArgBorderPixmap(ab, v)               ISW_ARG((ab), IswNborderPixmap, (v))
#define IswArgBorderWidth(ab, v)                ISW_ARG((ab), IswNborderWidth, (v))
#define IswArgCallback(ab, v)                   ISW_ARG((ab), IswNcallback, (v))
#define IswArgColormap(ab, v)                   ISW_ARG((ab), IswNcolormap, (v))
#define IswArgDepth(ab, v)                      ISW_ARG((ab), IswNdepth, (v))
#define IswArgDestroyCallback(ab, v)            ISW_ARG((ab), IswNdestroyCallback, (v))
#define IswArgEditType(ab, v)                   ISW_ARG((ab), IswNeditType, (v))
#define IswArgFile(ab, v)                       ISW_ARG((ab), IswNfile, (v))
#define IswArgFont(ab, v)                       ISW_ARG((ab), IswNfont, (v))
#define IswArgFontSet(ab, v)                    ISW_ARG((ab), IswNfontSet, (v))
#define IswArgForceBars(ab, v)                  ISW_ARG((ab), IswNforceBars, (v))
#define IswArgForeground(ab, v)                 ISW_ARG((ab), IswNforeground, (v))
#define IswArgFunction(ab, v)                   ISW_ARG((ab), IswNfunction, (v))
#define IswArgHeight(ab, v)                     ISW_ARG((ab), IswNheight, (v))
#define IswArgHighlight(ab, v)                  ISW_ARG((ab), IswNhighlight, (v))
#define IswArgHSpace(ab, v)                     ISW_ARG((ab), IswNhSpace, (v))
#define IswArgIndex(ab, v)                      ISW_ARG((ab), IswNindex, (v))
#define IswArgInitialResourcesPersistent(ab, v) ISW_ARG((ab), IswNinitialResourcesPersistent, (v))
#define IswArgInnerHeight(ab, v)                ISW_ARG((ab), IswNinnerHeight, (v))
#define IswArgInnerWidth(ab, v)                 ISW_ARG((ab), IswNinnerWidth, (v))
#define IswArgInnerWindow(ab, v)                ISW_ARG((ab), IswNinnerWindow, (v))
#define IswArgInsertPosition(ab, v)             ISW_ARG((ab), IswNinsertPosition, (v))
#define IswArgInternalHeight(ab, v)             ISW_ARG((ab), IswNinternalHeight, (v))
#define IswArgInternalWidth(ab, v)              ISW_ARG((ab), IswNinternalWidth, (v))
#define IswArgJumpProc(ab, v)                   ISW_ARG((ab), IswNjumpProc, (v))
#define IswArgJustify(ab, v)                    ISW_ARG((ab), IswNjustify, (v))
#define IswArgKnobHeight(ab, v)                 ISW_ARG((ab), IswNknobHeight, (v))
#define IswArgKnobIndent(ab, v)                 ISW_ARG((ab), IswNknobIndent, (v))
#define IswArgKnobPixel(ab, v)                  ISW_ARG((ab), IswNknobPixel, (v))
#define IswArgKnobWidth(ab, v)                  ISW_ARG((ab), IswNknobWidth, (v))
#define IswArgLabel(ab, v)                      ISW_ARG((ab), IswNlabel, (v))
#define IswArgLength(ab, v)                     ISW_ARG((ab), IswNlength, (v))
#define IswArgLowerRight(ab, v)                 ISW_ARG((ab), IswNlowerRight, (v))
#define IswArgMappedWhenManaged(ab, v)          ISW_ARG((ab), IswNmappedWhenManaged, (v))
#define IswArgMenuEntry(ab, v)                  ISW_ARG((ab), IswNmenuEntry, (v))
#define IswArgName(ab, v)                       ISW_ARG((ab), IswNname, (v))
#define IswArgNotify(ab, v)                     ISW_ARG((ab), IswNnotify, (v))
#define IswArgOrientation(ab, v)                ISW_ARG((ab), IswNorientation, (v))
#define IswArgParameter(ab, v)                  ISW_ARG((ab), IswNparameter, (v))
#define IswArgPixmap(ab, v)                     ISW_ARG((ab), IswNpixmap, (v))
#define IswArgPopdownCallback(ab, v)            ISW_ARG((ab), IswNpopdownCallback, (v))
#define IswArgPopupCallback(ab, v)              ISW_ARG((ab), IswNpopupCallback, (v))
#define IswArgResize(ab, v)                     ISW_ARG((ab), IswNresize, (v))
#define IswArgReverseVideo(ab, v)               ISW_ARG((ab), IswNreverseVideo, (v))
#define IswArgScreen(ab, v)                     ISW_ARG((ab), IswNscreen, (v))
#define IswArgScrollDCursor(ab, v)              ISW_ARG((ab), IswNscrollDCursor, (v))
#define IswArgScrollHCursor(ab, v)              ISW_ARG((ab), IswNscrollHCursor, (v))
#define IswArgScrollLCursor(ab, v)              ISW_ARG((ab), IswNscrollLCursor, (v))
#define IswArgScrollProc(ab, v)                 ISW_ARG((ab), IswNscrollProc, (v))
#define IswArgScrollRCursor(ab, v)              ISW_ARG((ab), IswNscrollRCursor, (v))
#define IswArgScrollUCursor(ab, v)              ISW_ARG((ab), IswNscrollUCursor, (v))
#define IswArgScrollVCursor(ab, v)              ISW_ARG((ab), IswNscrollVCursor, (v))
#define IswArgSelection(ab, v)                  ISW_ARG((ab), IswNselection, (v))
#define IswArgSelectionArray(ab, v)             ISW_ARG((ab), IswNselectionArray, (v))
#define IswArgSensitive(ab, v)                  ISW_ARG((ab), IswNsensitive, (v))
#define IswArgShown(ab, v)                      ISW_ARG((ab), IswNshown, (v))
#define IswArgSpace(ab, v)                      ISW_ARG((ab), IswNspace, (v))
#define IswArgString(ab, v)                     ISW_ARG((ab), IswNstring, (v))
#define IswArgTextOptions(ab, v)                ISW_ARG((ab), IswNtextOptions, (v))
#define IswArgTextSink(ab, v)                   ISW_ARG((ab), IswNtextSink, (v))
#define IswArgTextSource(ab, v)                 ISW_ARG((ab), IswNtextSource, (v))
#define IswArgThickness(ab, v)                  ISW_ARG((ab), IswNthickness, (v))
#define IswArgThumb(ab, v)                      ISW_ARG((ab), IswNthumb, (v))
#define IswArgThumbProc(ab, v)                  ISW_ARG((ab), IswNthumbProc, (v))
#define IswArgTop(ab, v)                        ISW_ARG((ab), IswNtop, (v))
#define IswArgTranslations(ab, v)               ISW_ARG((ab), IswNtranslations, (v))
#define IswArgUnrealizeCallback(ab, v)          ISW_ARG((ab), IswNunrealizeCallback, (v))
#define IswArgUpdate(ab, v)                     ISW_ARG((ab), IswNupdate, (v))
#define IswArgUseBottom(ab, v)                  ISW_ARG((ab), IswNuseBottom, (v))
#define IswArgUseRight(ab, v)                   ISW_ARG((ab), IswNuseRight, (v))
#define IswArgValue(ab, v)                      ISW_ARG((ab), IswNvalue, (v))
#define IswArgVSpace(ab, v)                     ISW_ARG((ab), IswNvSpace, (v))
#define IswArgWidth(ab, v)                      ISW_ARG((ab), IswNwidth, (v))
#define IswArgWindow(ab, v)                     ISW_ARG((ab), IswNwindow, (v))
#define IswArgX(ab, v)                          ISW_ARG((ab), IswNx, (v))
#define IswArgY(ab, v)                          ISW_ARG((ab), IswNy, (v))

/* Form — edge chain constraints take IswEdgeType (IswChainTop/Bottom/Left/Right/IswRubber) */
#define IswArgDefaultDistance(ab, v)            ISW_ARG((ab), IswNdefaultDistance, (v))
#define IswArgBottom(ab, v)                     ISW_ARG((ab), IswNbottom, (v))
#define IswArgLeft(ab, v)                       ISW_ARG((ab), IswNleft, (v))
#define IswArgRight(ab, v)                      ISW_ARG((ab), IswNright, (v))
#define IswArgFromHoriz(ab, v)                  ISW_ARG((ab), IswNfromHoriz, (v))
#define IswArgFromVert(ab, v)                   ISW_ARG((ab), IswNfromVert, (v))
#define IswArgHorizDistance(ab, v)              ISW_ARG((ab), IswNhorizDistance, (v))
#define IswArgVertDistance(ab, v)               ISW_ARG((ab), IswNvertDistance, (v))
#define IswArgResizable(ab, v)                  ISW_ARG((ab), IswNresizable, (v))

/* Shell */
#define IswArgIconName(ab, v)                   ISW_ARG((ab), IswNiconName, (v))
#define IswArgIconPixmap(ab, v)                 ISW_ARG((ab), IswNiconPixmap, (v))
#define IswArgIconWindow(ab, v)                 ISW_ARG((ab), IswNiconWindow, (v))
#define IswArgIconMask(ab, v)                   ISW_ARG((ab), IswNiconMask, (v))
#define IswArgWindowGroup(ab, v)                ISW_ARG((ab), IswNwindowGroup, (v))
#define IswArgVisual(ab, v)                     ISW_ARG((ab), IswNvisual, (v))
#define IswArgTitleEncoding(ab, v)              ISW_ARG((ab), IswNtitleEncoding, (v))
#define IswArgSaveUnder(ab, v)                  ISW_ARG((ab), IswNsaveUnder, (v))
#define IswArgTransient(ab, v)                  ISW_ARG((ab), IswNtransient, (v))
#define IswArgOverrideRedirect(ab, v)           ISW_ARG((ab), IswNoverrideRedirect, (v))
#define IswArgTransientFor(ab, v)               ISW_ARG((ab), IswNtransientFor, (v))
#define IswArgIconNameEncoding(ab, v)           ISW_ARG((ab), IswNiconNameEncoding, (v))
#define IswArgAllowShellResize(ab, v)           ISW_ARG((ab), IswNallowShellResize, (v))
#define IswArgCreatePopupChildProc(ab, v)       ISW_ARG((ab), IswNcreatePopupChildProc, (v))
#define IswArgTitle(ab, v)                      ISW_ARG((ab), IswNtitle, (v))
#define IswArgArgc(ab, v)                       ISW_ARG((ab), IswNargc, (v))
#define IswArgArgv(ab, v)                       ISW_ARG((ab), IswNargv, (v))
#define IswArgIconX(ab, v)                      ISW_ARG((ab), IswNiconX, (v))
#define IswArgIconY(ab, v)                      ISW_ARG((ab), IswNiconY, (v))
#define IswArgInput(ab, v)                      ISW_ARG((ab), IswNinput, (v))
#define IswArgIconic(ab, v)                     ISW_ARG((ab), IswNiconic, (v))
#define IswArgInitialState(ab, v)               ISW_ARG((ab), IswNinitialState, (v))
#define IswArgGeometry(ab, v)                   ISW_ARG((ab), IswNgeometry, (v))
#define IswArgBaseWidth(ab, v)                  ISW_ARG((ab), IswNbaseWidth, (v))
#define IswArgBaseHeight(ab, v)                 ISW_ARG((ab), IswNbaseHeight, (v))
#define IswArgWinGravity(ab, v)                 ISW_ARG((ab), IswNwinGravity, (v))
#define IswArgMinWidth(ab, v)                   ISW_ARG((ab), IswNminWidth, (v))
#define IswArgMinHeight(ab, v)                  ISW_ARG((ab), IswNminHeight, (v))
#define IswArgMaxWidth(ab, v)                   ISW_ARG((ab), IswNmaxWidth, (v))
#define IswArgMaxHeight(ab, v)                  ISW_ARG((ab), IswNmaxHeight, (v))
#define IswArgWidthInc(ab, v)                   ISW_ARG((ab), IswNwidthInc, (v))
#define IswArgHeightInc(ab, v)                  ISW_ARG((ab), IswNheightInc, (v))
#define IswArgMinAspectY(ab, v)                 ISW_ARG((ab), IswNminAspectY, (v))
#define IswArgMaxAspectY(ab, v)                 ISW_ARG((ab), IswNmaxAspectY, (v))
#define IswArgMinAspectX(ab, v)                 ISW_ARG((ab), IswNminAspectX, (v))
#define IswArgMaxAspectX(ab, v)                 ISW_ARG((ab), IswNmaxAspectX, (v))
#define IswArgWmTimeout(ab, v)                  ISW_ARG((ab), IswNwmTimeout, (v))
#define IswArgWaitForWm(ab, v)                  ISW_ARG((ab), IswNwaitForWm, (v))
#define IswArgClientLeader(ab, v)               ISW_ARG((ab), IswNclientLeader, (v))
#define IswArgWindowRole(ab, v)                 ISW_ARG((ab), IswNwindowRole, (v))
#define IswArgUrgency(ab, v)                    ISW_ARG((ab), IswNurgency, (v))

/* Text */
#define IswArgAutoFill(ab, v)                   ISW_ARG((ab), IswNautoFill, (v))
#define IswArgBottomMargin(ab, v)               ISW_ARG((ab), IswNbottomMargin, (v))
#define IswArgDialogHOffset(ab, v)              ISW_ARG((ab), IswNdialogHOffset, (v))
#define IswArgDialogVOffset(ab, v)              ISW_ARG((ab), IswNdialogVOffset, (v))
#define IswArgDisplayCaret(ab, v)               ISW_ARG((ab), IswNdisplayCaret, (v))
#define IswArgDisplayPosition(ab, v)            ISW_ARG((ab), IswNdisplayPosition, (v))
#define IswArgLeftMargin(ab, v)                 ISW_ARG((ab), IswNleftMargin, (v))
#define IswArgRightMargin(ab, v)                ISW_ARG((ab), IswNrightMargin, (v))
#define IswArgScrollVertical(ab, v)             ISW_ARG((ab), IswNscrollVertical, (v))
#define IswArgScrollHorizontal(ab, v)           ISW_ARG((ab), IswNscrollHorizontal, (v))
#define IswArgSelectTypes(ab, v)                ISW_ARG((ab), IswNselectTypes, (v))
#define IswArgTopMargin(ab, v)                  ISW_ARG((ab), IswNtopMargin, (v))
#define IswArgWrap(ab, v)                       ISW_ARG((ab), IswNwrap, (v))

/* Paned */
#define IswArgAllowResize(ab, v)                ISW_ARG((ab), IswNallowResize, (v))
#define IswArgBetweenCursor(ab, v)              ISW_ARG((ab), IswNbetweenCursor, (v))
#define IswArgVerticalBetweenCursor(ab, v)      ISW_ARG((ab), IswNverticalBetweenCursor, (v))
#define IswArgHorizontalBetweenCursor(ab, v)    ISW_ARG((ab), IswNhorizontalBetweenCursor, (v))
#define IswArgGripCursor(ab, v)                 ISW_ARG((ab), IswNgripCursor, (v))
#define IswArgGripIndent(ab, v)                 ISW_ARG((ab), IswNgripIndent, (v))
#define IswArgHorizontalGripCursor(ab, v)       ISW_ARG((ab), IswNhorizontalGripCursor, (v))
#define IswArgInternalBorderColor(ab, v)        ISW_ARG((ab), IswNinternalBorderColor, (v))
#define IswArgInternalBorderWidth(ab, v)        ISW_ARG((ab), IswNinternalBorderWidth, (v))
#define IswArgLeftCursor(ab, v)                 ISW_ARG((ab), IswNleftCursor, (v))
#define IswArgLowerCursor(ab, v)                ISW_ARG((ab), IswNlowerCursor, (v))
#define IswArgRefigureMode(ab, v)               ISW_ARG((ab), IswNrefigureMode, (v))
#define IswArgPosition(ab, v)                   ISW_ARG((ab), IswNposition, (v))
#define IswArgMin(ab, v)                        ISW_ARG((ab), IswNmin, (v))
#define IswArgMax(ab, v)                        ISW_ARG((ab), IswNmax, (v))
#define IswArgPreferredPaneSize(ab, v)          ISW_ARG((ab), IswNpreferredPaneSize, (v))
#define IswArgResizeToPreferred(ab, v)          ISW_ARG((ab), IswNresizeToPreferred, (v))
#define IswArgRightCursor(ab, v)                ISW_ARG((ab), IswNrightCursor, (v))
#define IswArgShowGrip(ab, v)                   ISW_ARG((ab), IswNshowGrip, (v))
#define IswArgSkipAdjust(ab, v)                 ISW_ARG((ab), IswNskipAdjust, (v))
#define IswArgUpperCursor(ab, v)                ISW_ARG((ab), IswNupperCursor, (v))
#define IswArgVerticalGripCursor(ab, v)         ISW_ARG((ab), IswNverticalGripCursor, (v))

/* Panner */
#define IswArgAllowOff(ab, v)                   ISW_ARG((ab), IswNallowOff, (v))
#define IswArgBackgroundStipple(ab, v)          ISW_ARG((ab), IswNbackgroundStipple, (v))
#define IswArgDefaultScale(ab, v)               ISW_ARG((ab), IswNdefaultScale, (v))
#define IswArgCanvasWidth(ab, v)                ISW_ARG((ab), IswNcanvasWidth, (v))
#define IswArgCanvasHeight(ab, v)               ISW_ARG((ab), IswNcanvasHeight, (v))
#define IswArgInternalSpace(ab, v)              ISW_ARG((ab), IswNinternalSpace, (v))
#define IswArgLineWidth(ab, v)                  ISW_ARG((ab), IswNlineWidth, (v))
#define IswArgRubberBand(ab, v)                 ISW_ARG((ab), IswNrubberBand, (v))
#define IswArgSliderX(ab, v)                    ISW_ARG((ab), IswNsliderX, (v))
#define IswArgSliderY(ab, v)                    ISW_ARG((ab), IswNsliderY, (v))
#define IswArgSliderWidth(ab, v)                ISW_ARG((ab), IswNsliderWidth, (v))
#define IswArgSliderHeight(ab, v)               ISW_ARG((ab), IswNsliderHeight, (v))

/* List */
#define IswArgCursor(ab, v)                     ISW_ARG((ab), IswNcursor, (v))
#define IswArgColumnSpacing(ab, v)              ISW_ARG((ab), IswNcolumnSpacing, (v))
#define IswArgDefaultColumns(ab, v)             ISW_ARG((ab), IswNdefaultColumns, (v))
#define IswArgForceColumns(ab, v)               ISW_ARG((ab), IswNforceColumns, (v))
#define IswArgList(ab, v)                       ISW_ARG((ab), IswNlist, (v))
#define IswArgLongest(ab, v)                    ISW_ARG((ab), IswNlongest, (v))
#define IswArgNumberStrings(ab, v)              ISW_ARG((ab), IswNnumberStrings, (v))
#define IswArgPasteBuffer(ab, v)                ISW_ARG((ab), IswNpasteBuffer, (v))
#define IswArgRowSpacing(ab, v)                 ISW_ARG((ab), IswNrowSpacing, (v))
#define IswArgVerticalList(ab, v)               ISW_ARG((ab), IswNverticalList, (v))
#define IswArgDropdownMode(ab, v)               ISW_ARG((ab), IswNdropdownMode, (v))

/* Scrollbar */
#define IswArgMinimumThumb(ab, v)               ISW_ARG((ab), IswNminimumThumb, (v))
#define IswArgTopOfThumb(ab, v)                 ISW_ARG((ab), IswNtopOfThumb, (v))
#define IswArgPickTop(ab, v)                    ISW_ARG((ab), IswNpickTop, (v))
#define IswArgScrollWheelIncrement(ab, v)       ISW_ARG((ab), IswNscrollWheelIncrement, (v))

/* Slider */
#define IswArgMinimumValue(ab, v)               ISW_ARG((ab), IswNminimumValue, (v))
#define IswArgMaximumValue(ab, v)               ISW_ARG((ab), IswNmaximumValue, (v))
#define IswArgSliderValue(ab, v)                ISW_ARG((ab), IswNsliderValue, (v))
#define IswArgShowValue(ab, v)                  ISW_ARG((ab), IswNshowValue, (v))
#define IswArgValueChanged(ab, v)               ISW_ARG((ab), IswNvalueChanged, (v))
#define IswArgValuePosition(ab, v)              ISW_ARG((ab), IswNvaluePosition, (v))
#define IswArgTickInterval(ab, v)               ISW_ARG((ab), IswNtickInterval, (v))

/* SpinBox */
#define IswArgSpinMinimum(ab, v)                ISW_ARG((ab), IswNspinMinimum, (v))
#define IswArgSpinMaximum(ab, v)                ISW_ARG((ab), IswNspinMaximum, (v))
#define IswArgSpinValue(ab, v)                  ISW_ARG((ab), IswNspinValue, (v))
#define IswArgSpinIncrement(ab, v)              ISW_ARG((ab), IswNspinIncrement, (v))
#define IswArgSpinWrap(ab, v)                   ISW_ARG((ab), IswNspinWrap, (v))

/* ColorPicker */
#define IswArgColorRed(ab, v)                   ISW_ARG((ab), IswNcolorRed, (v))
#define IswArgColorGreen(ab, v)                 ISW_ARG((ab), IswNcolorGreen, (v))
#define IswArgColorBlue(ab, v)                  ISW_ARG((ab), IswNcolorBlue, (v))
#define IswArgColorChanged(ab, v)               ISW_ARG((ab), IswNcolorChanged, (v))

/* FontChooser */
#define IswArgFontFamily(ab, v)                 ISW_ARG((ab), IswNfontFamily, (v))
#define IswArgFontSize(ab, v)                   ISW_ARG((ab), IswNfontSize, (v))
#define IswArgFontWeight(ab, v)                 ISW_ARG((ab), IswNfontWeight, (v))
#define IswArgFontSlant(ab, v)                  ISW_ARG((ab), IswNfontSlant, (v))
#define IswArgPreviewText(ab, v)                ISW_ARG((ab), IswNpreviewText, (v))
#define IswArgFontChanged(ab, v)                ISW_ARG((ab), IswNfontChanged, (v))

/* FlexBox */
#define IswArgSpacing(ab, v)                    ISW_ARG((ab), IswNspacing, (v))
#define IswArgFlexGrow(ab, v)                   ISW_ARG((ab), IswNflexGrow, (v))
#define IswArgFlexBasis(ab, v)                  ISW_ARG((ab), IswNflexBasis, (v))
#define IswArgFlexAlign(ab, v)                  ISW_ARG((ab), IswNflexAlign, (v))

/* Tree */
#define IswArgAutoReconfigure(ab, v)            ISW_ARG((ab), IswNautoReconfigure, (v))
#define IswArgTreeForeground(ab, v)             ISW_ARG((ab), IswNtreeForeground, (v))
#define IswArgTreeParent(ab, v)                 ISW_ARG((ab), IswNtreeParent, (v))
#define IswArgGravity(ab, v)                    ISW_ARG((ab), IswNgravity, (v))

/* IconView */
#define IswArgIconLabels(ab, v)                 ISW_ARG((ab), IswNiconLabels, (v))
#define IswArgIconData(ab, v)                   ISW_ARG((ab), IswNiconData, (v))
#define IswArgNumIcons(ab, v)                   ISW_ARG((ab), IswNnumIcons, (v))
#define IswArgIconSize(ab, v)                   ISW_ARG((ab), IswNiconSize, (v))
#define IswArgItemSpacing(ab, v)                ISW_ARG((ab), IswNitemSpacing, (v))
#define IswArgLabelLines(ab, v)                 ISW_ARG((ab), IswNlabelLines, (v))
#define IswArgSelectCallback(ab, v)             ISW_ARG((ab), IswNselectCallback, (v))
#define IswArgMultiSelect(ab, v)                ISW_ARG((ab), IswNmultiSelect, (v))
#define IswArgCursorItem(ab, v)                 ISW_ARG((ab), IswNcursorItem, (v))

/* ListView */
#define IswArgListViewColumns(ab, v)            ISW_ARG((ab), IswNlistViewColumns, (v))
#define IswArgNumColumns(ab, v)                 ISW_ARG((ab), IswNnumColumns, (v))
#define IswArgNumRows(ab, v)                    ISW_ARG((ab), IswNnumRows, (v))
#define IswArgListViewData(ab, v)               ISW_ARG((ab), IswNlistViewData, (v))
#define IswArgRowHeight(ab, v)                  ISW_ARG((ab), IswNrowHeight, (v))
#define IswArgHeaderHeight(ab, v)               ISW_ARG((ab), IswNheaderHeight, (v))
#define IswArgCursorRow(ab, v)                  ISW_ARG((ab), IswNcursorRow, (v))
#define IswArgShowHeader(ab, v)                 ISW_ARG((ab), IswNshowHeader, (v))
#define IswArgReorderCallback(ab, v)            ISW_ARG((ab), IswNreorderCallback, (v))

/* Command */
#define IswArgBorderStrokeWidth(ab, v)          ISW_ARG((ab), IswNborderStrokeWidth, (v))
#define IswArgHighlightThickness(ab, v)         ISW_ARG((ab), IswNhighlightThickness, (v))
#define IswArgShapeStyle(ab, v)                 ISW_ARG((ab), IswNshapeStyle, (v))
#define IswArgCornerRadius(ab, v)               ISW_ARG((ab), IswNcornerRadius, (v))

/* Toggle */
#define IswArgState(ab, v)                      ISW_ARG((ab), IswNstate, (v))
#define IswArgRadioGroup(ab, v)                 ISW_ARG((ab), IswNradioGroup, (v))
#define IswArgRadioData(ab, v)                  ISW_ARG((ab), IswNradioData, (v))

/* Tabs */
#define IswArgTabCallback(ab, v)                ISW_ARG((ab), IswNtabCallback, (v))
#define IswArgTopWidget(ab, v)                  ISW_ARG((ab), IswNtopWidget, (v))
#define IswArgTabLabel(ab, v)                   ISW_ARG((ab), IswNtabLabel, (v))

/* Repeater */
#define IswArgDecay(ab, v)                      ISW_ARG((ab), IswNdecay, (v))
#define IswArgInitialDelay(ab, v)               ISW_ARG((ab), IswNinitialDelay, (v))
#define IswArgMinimumDelay(ab, v)               ISW_ARG((ab), IswNminimumDelay, (v))
#define IswArgRepeatDelay(ab, v)                ISW_ARG((ab), IswNrepeatDelay, (v))
#define IswArgFlash(ab, v)                      ISW_ARG((ab), IswNflash, (v))
#define IswArgStartCallback(ab, v)              ISW_ARG((ab), IswNstartCallback, (v))
#define IswArgStopCallback(ab, v)               ISW_ARG((ab), IswNstopCallback, (v))

/* StatusBar / Toolbar / MenuButton */
#define IswArgStatusStretch(ab, v)              ISW_ARG((ab), IswNstatusStretch, (v))
#define IswArgToolbarAlignment(ab, v)           ISW_ARG((ab), IswNtoolbarAlignment, (v))
#define IswArgMenuName(ab, v)                   ISW_ARG((ab), IswNmenuName, (v))

/* SimpleMenu */
#define IswArgColumnWidth(ab, v)                ISW_ARG((ab), IswNcolumnWidth, (v))
#define IswArgLabelClass(ab, v)                 ISW_ARG((ab), IswNlabelClass, (v))
#define IswArgMenuOnScreen(ab, v)               ISW_ARG((ab), IswNmenuOnScreen, (v))
#define IswArgPopupOnEntry(ab, v)               ISW_ARG((ab), IswNpopupOnEntry, (v))

/* Simple */
#define IswArgCursorName(ab, v)                 ISW_ARG((ab), IswNcursorName, (v))
#define IswArgInsensitiveBorder(ab, v)          ISW_ARG((ab), IswNinsensitiveBorder, (v))
#define IswArgInternational(ab, v)              ISW_ARG((ab), IswNinternational, (v))

/* Label */
#define IswArgImage(ab, v)                      ISW_ARG((ab), IswNimage, (v))
#define IswArgLeftImage(ab, v)                  ISW_ARG((ab), IswNleftImage, (v))
#define IswArgEncoding(ab, v)                   ISW_ARG((ab), IswNencoding, (v))

/* Tip */
#define IswArgTimeout(ab, v)                    ISW_ARG((ab), IswNtimeout, (v))
#define IswArgTip(ab, v)                        ISW_ARG((ab), IswNtip, (v))

/* DrawingArea */
#define IswArgExposeCallback(ab, v)             ISW_ARG((ab), IswNexposeCallback, (v))
#define IswArgResizeCallback(ab, v)             ISW_ARG((ab), IswNresizeCallback, (v))
#define IswArgInputCallback(ab, v)              ISW_ARG((ab), IswNinputCallback, (v))

/* Dialog / Layout / Template / Reports / ProgressBar / Grip */
#define IswArgIcon(ab, v)                       ISW_ARG((ab), IswNicon, (v))
#define IswArgLayout(ab, v)                     ISW_ARG((ab), IswNlayout, (v))
#define IswArgDebug(ab, v)                      ISW_ARG((ab), IswNdebug, (v))
#define IswArgTemplateResource(ab, v)           ISW_ARG((ab), IswNtemplateResource, (v))
#define IswArgReportCallback(ab, v)             ISW_ARG((ab), IswNreportCallback, (v))
#define IswArgGripTranslations(ab, v)           ISW_ARG((ab), IswNgripTranslations, (v))

/* AsciiSrc / MultiSrc */
#define IswArgDataCompression(ab, v)            ISW_ARG((ab), IswNdataCompression, (v))
#define IswArgPieceSize(ab, v)                  ISW_ARG((ab), IswNpieceSize, (v))
#define IswArgType(ab, v)                       ISW_ARG((ab), IswNtype, (v))
#define IswArgUseStringInPlace(ab, v)           ISW_ARG((ab), IswNuseStringInPlace, (v))

/* AsciiSink / MultiSink */
#define IswArgDisplayNonprinting(ab, v)         ISW_ARG((ab), IswNdisplayNonprinting, (v))
#define IswArgEcho(ab, v)                       ISW_ARG((ab), IswNecho, (v))

/* ISWImP */
#define IswArgInputMethod(ab, v)                ISW_ARG((ab), IswNinputMethod, (v))
#define IswArgPreeditType(ab, v)                ISW_ARG((ab), IswNpreeditType, (v))
#define IswArgOpenIm(ab, v)                     ISW_ARG((ab), IswNopenIm, (v))
#define IswArgSharedIc(ab, v)                   ISW_ARG((ab), IswNsharedIc, (v))

/* ISWXdnd */
#define IswArgDropCallback(ab, v)               ISW_ARG((ab), IswNdropCallback, (v))
#define IswArgDragEnterCallback(ab, v)          ISW_ARG((ab), IswNdragEnterCallback, (v))
#define IswArgDragMotionCallback(ab, v)         ISW_ARG((ab), IswNdragMotionCallback, (v))
#define IswArgDragLeaveCallback(ab, v)          ISW_ARG((ab), IswNdragLeaveCallback, (v))

#endif /* _IswArgMacros_h */
