#ifndef _IswArgMacros_h
#define _IswArgMacros_h

#include <ISW/Intrinsic.h>
#include <ISW/StringDefs.h>
#include <ISW/Shell.h>
#include <ISW/Form.h>

#define ISW_ARG(ab, name, v) IswArgBuilderAdd((ab), (name), (IswArgVal)(v))

/* Core (StringDefs.h) */
#define IswSetAccelerators(ab, v)               ISW_ARG((ab), IswNaccelerators, (v))
#define IswSetAllowHoriz(ab, v)                 ISW_ARG((ab), IswNallowHoriz, (v))
#define IswSetAllowVert(ab, v)                  ISW_ARG((ab), IswNallowVert, (v))
#define IswSetAncestorSensitive(ab, v)          ISW_ARG((ab), IswNancestorSensitive, (v))
#define IswSetBackground(ab, v)                 ISW_ARG((ab), IswNbackground, (v))
#define IswSetBackgroundPixmap(ab, v)           ISW_ARG((ab), IswNbackgroundPixmap, (v))
#define IswSetBitmap(ab, v)                     ISW_ARG((ab), IswNbitmap, (v))
#define IswSetBorder(ab, v)                     ISW_ARG((ab), IswNborder, (v))
#define IswSetBorderColor(ab, v)                ISW_ARG((ab), IswNborderColor, (v))
#define IswSetBorderPixmap(ab, v)               ISW_ARG((ab), IswNborderPixmap, (v))
#define IswSetBorderWidth(ab, v)                ISW_ARG((ab), IswNborderWidth, (v))
#define IswSetCallback(ab, v)                   ISW_ARG((ab), IswNcallback, (v))
#define IswSetColormap(ab, v)                   ISW_ARG((ab), IswNcolormap, (v))
#define IswSetDepth(ab, v)                      ISW_ARG((ab), IswNdepth, (v))
#define IswSetDestroyCallback(ab, v)            ISW_ARG((ab), IswNdestroyCallback, (v))
#define IswSetEditType(ab, v)                   ISW_ARG((ab), IswNeditType, (v))
#define IswSetFile(ab, v)                       ISW_ARG((ab), IswNfile, (v))
#define IswSetFont(ab, v)                       ISW_ARG((ab), IswNfont, (v))
#define IswSetFontSet(ab, v)                    ISW_ARG((ab), IswNfontSet, (v))
#define IswSetForceBars(ab, v)                  ISW_ARG((ab), IswNforceBars, (v))
#define IswSetForeground(ab, v)                 ISW_ARG((ab), IswNforeground, (v))
#define IswSetFunction(ab, v)                   ISW_ARG((ab), IswNfunction, (v))
#define IswSetHeight(ab, v)                     ISW_ARG((ab), IswNheight, (v))
#define IswSetHighlight(ab, v)                  ISW_ARG((ab), IswNhighlight, (v))
#define IswSetHSpace(ab, v)                     ISW_ARG((ab), IswNhSpace, (v))
#define IswSetIndex(ab, v)                      ISW_ARG((ab), IswNindex, (v))
#define IswSetInitialResourcesPersistent(ab, v) ISW_ARG((ab), IswNinitialResourcesPersistent, (v))
#define IswSetInnerHeight(ab, v)                ISW_ARG((ab), IswNinnerHeight, (v))
#define IswSetInnerWidth(ab, v)                 ISW_ARG((ab), IswNinnerWidth, (v))
#define IswSetInnerWindow(ab, v)                ISW_ARG((ab), IswNinnerWindow, (v))
#define IswSetInsertPosition(ab, v)             ISW_ARG((ab), IswNinsertPosition, (v))
#define IswSetInternalHeight(ab, v)             ISW_ARG((ab), IswNinternalHeight, (v))
#define IswSetInternalWidth(ab, v)              ISW_ARG((ab), IswNinternalWidth, (v))
#define IswSetJumpProc(ab, v)                   ISW_ARG((ab), IswNjumpProc, (v))
#define IswSetJustify(ab, v)                    ISW_ARG((ab), IswNjustify, (v))
#define IswSetKnobHeight(ab, v)                 ISW_ARG((ab), IswNknobHeight, (v))
#define IswSetKnobIndent(ab, v)                 ISW_ARG((ab), IswNknobIndent, (v))
#define IswSetKnobPixel(ab, v)                  ISW_ARG((ab), IswNknobPixel, (v))
#define IswSetKnobWidth(ab, v)                  ISW_ARG((ab), IswNknobWidth, (v))
#define IswSetLabel(ab, v)                      ISW_ARG((ab), IswNlabel, (v))
#define IswSetLength(ab, v)                     ISW_ARG((ab), IswNlength, (v))
#define IswSetLowerRight(ab, v)                 ISW_ARG((ab), IswNlowerRight, (v))
#define IswSetMappedWhenManaged(ab, v)          ISW_ARG((ab), IswNmappedWhenManaged, (v))
#define IswSetMenuEntry(ab, v)                  ISW_ARG((ab), IswNmenuEntry, (v))
#define IswSetName(ab, v)                       ISW_ARG((ab), IswNname, (v))
#define IswSetNotify(ab, v)                     ISW_ARG((ab), IswNnotify, (v))
#define IswSetOrientation(ab, v)                ISW_ARG((ab), IswNorientation, (v))
#define IswSetParameter(ab, v)                  ISW_ARG((ab), IswNparameter, (v))
#define IswSetPixmap(ab, v)                     ISW_ARG((ab), IswNpixmap, (v))
#define IswSetPopdownCallback(ab, v)            ISW_ARG((ab), IswNpopdownCallback, (v))
#define IswSetPopupCallback(ab, v)              ISW_ARG((ab), IswNpopupCallback, (v))
#define IswSetResize(ab, v)                     ISW_ARG((ab), IswNresize, (v))
#define IswSetReverseVideo(ab, v)               ISW_ARG((ab), IswNreverseVideo, (v))
#define IswSetScreen(ab, v)                     ISW_ARG((ab), IswNscreen, (v))
#define IswSetScrollDCursor(ab, v)              ISW_ARG((ab), IswNscrollDCursor, (v))
#define IswSetScrollHCursor(ab, v)              ISW_ARG((ab), IswNscrollHCursor, (v))
#define IswSetScrollLCursor(ab, v)              ISW_ARG((ab), IswNscrollLCursor, (v))
#define IswSetScrollProc(ab, v)                 ISW_ARG((ab), IswNscrollProc, (v))
#define IswSetScrollRCursor(ab, v)              ISW_ARG((ab), IswNscrollRCursor, (v))
#define IswSetScrollUCursor(ab, v)              ISW_ARG((ab), IswNscrollUCursor, (v))
#define IswSetScrollVCursor(ab, v)              ISW_ARG((ab), IswNscrollVCursor, (v))
#define IswSetSelection(ab, v)                  ISW_ARG((ab), IswNselection, (v))
#define IswSetSelectionArray(ab, v)             ISW_ARG((ab), IswNselectionArray, (v))
#define IswSetSensitive(ab, v)                  ISW_ARG((ab), IswNsensitive, (v))
#define IswSetShown(ab, v)                      ISW_ARG((ab), IswNshown, (v))
#define IswSetSpace(ab, v)                      ISW_ARG((ab), IswNspace, (v))
#define IswSetString(ab, v)                     ISW_ARG((ab), IswNstring, (v))
#define IswSetTextOptions(ab, v)                ISW_ARG((ab), IswNtextOptions, (v))
#define IswSetTextSink(ab, v)                   ISW_ARG((ab), IswNtextSink, (v))
#define IswSetTextSource(ab, v)                 ISW_ARG((ab), IswNtextSource, (v))
#define IswSetThickness(ab, v)                  ISW_ARG((ab), IswNthickness, (v))
#define IswSetThumb(ab, v)                      ISW_ARG((ab), IswNthumb, (v))
#define IswSetThumbProc(ab, v)                  ISW_ARG((ab), IswNthumbProc, (v))
#define IswSetTop(ab, v)                        ISW_ARG((ab), IswNtop, (v))
#define IswSetTranslations(ab, v)               ISW_ARG((ab), IswNtranslations, (v))
#define IswSetUnrealizeCallback(ab, v)          ISW_ARG((ab), IswNunrealizeCallback, (v))
#define IswSetUpdate(ab, v)                     ISW_ARG((ab), IswNupdate, (v))
#define IswSetUseBottom(ab, v)                  ISW_ARG((ab), IswNuseBottom, (v))
#define IswSetUseRight(ab, v)                   ISW_ARG((ab), IswNuseRight, (v))
#define IswSetValue(ab, v)                      ISW_ARG((ab), IswNvalue, (v))
#define IswSetVSpace(ab, v)                     ISW_ARG((ab), IswNvSpace, (v))
#define IswSetWidth(ab, v)                      ISW_ARG((ab), IswNwidth, (v))
#define IswSetWindow(ab, v)                     ISW_ARG((ab), IswNwindow, (v))
#define IswSetX(ab, v)                          ISW_ARG((ab), IswNx, (v))
#define IswSetY(ab, v)                          ISW_ARG((ab), IswNy, (v))

/* Form — edge chain constraints take IswEdgeType (IswChainTop/Bottom/Left/Right/IswRubber) */
#define IswSetDefaultDistance(ab, v)            ISW_ARG((ab), IswNdefaultDistance, (v))
#define IswSetBottom(ab, v)                     ISW_ARG((ab), IswNbottom, (v))
#define IswSetLeft(ab, v)                       ISW_ARG((ab), IswNleft, (v))
#define IswSetRight(ab, v)                      ISW_ARG((ab), IswNright, (v))
#define IswSetFromHoriz(ab, v)                  ISW_ARG((ab), IswNfromHoriz, (v))
#define IswSetFromVert(ab, v)                   ISW_ARG((ab), IswNfromVert, (v))
#define IswSetHorizDistance(ab, v)              ISW_ARG((ab), IswNhorizDistance, (v))
#define IswSetVertDistance(ab, v)               ISW_ARG((ab), IswNvertDistance, (v))
#define IswSetResizable(ab, v)                  ISW_ARG((ab), IswNresizable, (v))

/* Shell */
#define IswSetIconName(ab, v)                   ISW_ARG((ab), IswNiconName, (v))
#define IswSetIconPixmap(ab, v)                 ISW_ARG((ab), IswNiconPixmap, (v))
#define IswSetIconWindow(ab, v)                 ISW_ARG((ab), IswNiconWindow, (v))
#define IswSetIconMask(ab, v)                   ISW_ARG((ab), IswNiconMask, (v))
#define IswSetWindowGroup(ab, v)                ISW_ARG((ab), IswNwindowGroup, (v))
#define IswSetVisual(ab, v)                     ISW_ARG((ab), IswNvisual, (v))
#define IswSetTitleEncoding(ab, v)              ISW_ARG((ab), IswNtitleEncoding, (v))
#define IswSetSaveUnder(ab, v)                  ISW_ARG((ab), IswNsaveUnder, (v))
#define IswSetTransient(ab, v)                  ISW_ARG((ab), IswNtransient, (v))
#define IswSetOverrideRedirect(ab, v)           ISW_ARG((ab), IswNoverrideRedirect, (v))
#define IswSetTransientFor(ab, v)               ISW_ARG((ab), IswNtransientFor, (v))
#define IswSetIconNameEncoding(ab, v)           ISW_ARG((ab), IswNiconNameEncoding, (v))
#define IswSetAllowShellResize(ab, v)           ISW_ARG((ab), IswNallowShellResize, (v))
#define IswSetCreatePopupChildProc(ab, v)       ISW_ARG((ab), IswNcreatePopupChildProc, (v))
#define IswSetTitle(ab, v)                      ISW_ARG((ab), IswNtitle, (v))
#define IswSetArgc(ab, v)                       ISW_ARG((ab), IswNargc, (v))
#define IswSetArgv(ab, v)                       ISW_ARG((ab), IswNargv, (v))
#define IswSetIconX(ab, v)                      ISW_ARG((ab), IswNiconX, (v))
#define IswSetIconY(ab, v)                      ISW_ARG((ab), IswNiconY, (v))
#define IswSetInput(ab, v)                      ISW_ARG((ab), IswNinput, (v))
#define IswSetIconic(ab, v)                     ISW_ARG((ab), IswNiconic, (v))
#define IswSetInitialState(ab, v)               ISW_ARG((ab), IswNinitialState, (v))
#define IswSetGeometry(ab, v)                   ISW_ARG((ab), IswNgeometry, (v))
#define IswSetBaseWidth(ab, v)                  ISW_ARG((ab), IswNbaseWidth, (v))
#define IswSetBaseHeight(ab, v)                 ISW_ARG((ab), IswNbaseHeight, (v))
#define IswSetWinGravity(ab, v)                 ISW_ARG((ab), IswNwinGravity, (v))
#define IswSetMinWidth(ab, v)                   ISW_ARG((ab), IswNminWidth, (v))
#define IswSetMinHeight(ab, v)                  ISW_ARG((ab), IswNminHeight, (v))
#define IswSetMaxWidth(ab, v)                   ISW_ARG((ab), IswNmaxWidth, (v))
#define IswSetMaxHeight(ab, v)                  ISW_ARG((ab), IswNmaxHeight, (v))
#define IswSetWidthInc(ab, v)                   ISW_ARG((ab), IswNwidthInc, (v))
#define IswSetHeightInc(ab, v)                  ISW_ARG((ab), IswNheightInc, (v))
#define IswSetMinAspectY(ab, v)                 ISW_ARG((ab), IswNminAspectY, (v))
#define IswSetMaxAspectY(ab, v)                 ISW_ARG((ab), IswNmaxAspectY, (v))
#define IswSetMinAspectX(ab, v)                 ISW_ARG((ab), IswNminAspectX, (v))
#define IswSetMaxAspectX(ab, v)                 ISW_ARG((ab), IswNmaxAspectX, (v))
#define IswSetWmTimeout(ab, v)                  ISW_ARG((ab), IswNwmTimeout, (v))
#define IswSetWaitForWm(ab, v)                  ISW_ARG((ab), IswNwaitForWm, (v))
#define IswSetClientLeader(ab, v)               ISW_ARG((ab), IswNclientLeader, (v))
#define IswSetWindowRole(ab, v)                 ISW_ARG((ab), IswNwindowRole, (v))
#define IswSetUrgency(ab, v)                    ISW_ARG((ab), IswNurgency, (v))

/* Text */
#define IswSetAutoFill(ab, v)                   ISW_ARG((ab), IswNautoFill, (v))
#define IswSetBottomMargin(ab, v)               ISW_ARG((ab), IswNbottomMargin, (v))
#define IswSetDialogHOffset(ab, v)              ISW_ARG((ab), IswNdialogHOffset, (v))
#define IswSetDialogVOffset(ab, v)              ISW_ARG((ab), IswNdialogVOffset, (v))
#define IswSetDisplayCaret(ab, v)               ISW_ARG((ab), IswNdisplayCaret, (v))
#define IswSetDisplayPosition(ab, v)            ISW_ARG((ab), IswNdisplayPosition, (v))
#define IswSetLeftMargin(ab, v)                 ISW_ARG((ab), IswNleftMargin, (v))
#define IswSetRightMargin(ab, v)                ISW_ARG((ab), IswNrightMargin, (v))
#define IswSetScrollVertical(ab, v)             ISW_ARG((ab), IswNscrollVertical, (v))
#define IswSetScrollHorizontal(ab, v)           ISW_ARG((ab), IswNscrollHorizontal, (v))
#define IswSetSelectTypes(ab, v)                ISW_ARG((ab), IswNselectTypes, (v))
#define IswSetTopMargin(ab, v)                  ISW_ARG((ab), IswNtopMargin, (v))
#define IswSetWrap(ab, v)                       ISW_ARG((ab), IswNwrap, (v))

/* Paned */
#define IswSetAllowResize(ab, v)                ISW_ARG((ab), IswNallowResize, (v))
#define IswSetBetweenCursor(ab, v)              ISW_ARG((ab), IswNbetweenCursor, (v))
#define IswSetVerticalBetweenCursor(ab, v)      ISW_ARG((ab), IswNverticalBetweenCursor, (v))
#define IswSetHorizontalBetweenCursor(ab, v)    ISW_ARG((ab), IswNhorizontalBetweenCursor, (v))
#define IswSetGripCursor(ab, v)                 ISW_ARG((ab), IswNgripCursor, (v))
#define IswSetGripIndent(ab, v)                 ISW_ARG((ab), IswNgripIndent, (v))
#define IswSetHorizontalGripCursor(ab, v)       ISW_ARG((ab), IswNhorizontalGripCursor, (v))
#define IswSetInternalBorderColor(ab, v)        ISW_ARG((ab), IswNinternalBorderColor, (v))
#define IswSetInternalBorderWidth(ab, v)        ISW_ARG((ab), IswNinternalBorderWidth, (v))
#define IswSetLeftCursor(ab, v)                 ISW_ARG((ab), IswNleftCursor, (v))
#define IswSetLowerCursor(ab, v)                ISW_ARG((ab), IswNlowerCursor, (v))
#define IswSetRefigureMode(ab, v)               ISW_ARG((ab), IswNrefigureMode, (v))
#define IswSetPosition(ab, v)                   ISW_ARG((ab), IswNposition, (v))
#define IswSetMin(ab, v)                        ISW_ARG((ab), IswNmin, (v))
#define IswSetMax(ab, v)                        ISW_ARG((ab), IswNmax, (v))
#define IswSetPreferredPaneSize(ab, v)          ISW_ARG((ab), IswNpreferredPaneSize, (v))
#define IswSetResizeToPreferred(ab, v)          ISW_ARG((ab), IswNresizeToPreferred, (v))
#define IswSetRightCursor(ab, v)                ISW_ARG((ab), IswNrightCursor, (v))
#define IswSetShowGrip(ab, v)                   ISW_ARG((ab), IswNshowGrip, (v))
#define IswSetSkipAdjust(ab, v)                 ISW_ARG((ab), IswNskipAdjust, (v))
#define IswSetUpperCursor(ab, v)                ISW_ARG((ab), IswNupperCursor, (v))
#define IswSetVerticalGripCursor(ab, v)         ISW_ARG((ab), IswNverticalGripCursor, (v))

/* Panner */
#define IswSetAllowOff(ab, v)                   ISW_ARG((ab), IswNallowOff, (v))
#define IswSetBackgroundStipple(ab, v)          ISW_ARG((ab), IswNbackgroundStipple, (v))
#define IswSetDefaultScale(ab, v)               ISW_ARG((ab), IswNdefaultScale, (v))
#define IswSetCanvasWidth(ab, v)                ISW_ARG((ab), IswNcanvasWidth, (v))
#define IswSetCanvasHeight(ab, v)               ISW_ARG((ab), IswNcanvasHeight, (v))
#define IswSetInternalSpace(ab, v)              ISW_ARG((ab), IswNinternalSpace, (v))
#define IswSetLineWidth(ab, v)                  ISW_ARG((ab), IswNlineWidth, (v))
#define IswSetRubberBand(ab, v)                 ISW_ARG((ab), IswNrubberBand, (v))
#define IswSetSliderX(ab, v)                    ISW_ARG((ab), IswNsliderX, (v))
#define IswSetSliderY(ab, v)                    ISW_ARG((ab), IswNsliderY, (v))
#define IswSetSliderWidth(ab, v)                ISW_ARG((ab), IswNsliderWidth, (v))
#define IswSetSliderHeight(ab, v)               ISW_ARG((ab), IswNsliderHeight, (v))

/* List */
#define IswSetCursor(ab, v)                     ISW_ARG((ab), IswNcursor, (v))
#define IswSetColumnSpacing(ab, v)              ISW_ARG((ab), IswNcolumnSpacing, (v))
#define IswSetDefaultColumns(ab, v)             ISW_ARG((ab), IswNdefaultColumns, (v))
#define IswSetForceColumns(ab, v)               ISW_ARG((ab), IswNforceColumns, (v))
#define IswSetList(ab, v)                       ISW_ARG((ab), IswNlist, (v))
#define IswSetLongest(ab, v)                    ISW_ARG((ab), IswNlongest, (v))
#define IswSetNumberStrings(ab, v)              ISW_ARG((ab), IswNnumberStrings, (v))
#define IswSetPasteBuffer(ab, v)                ISW_ARG((ab), IswNpasteBuffer, (v))
#define IswSetRowSpacing(ab, v)                 ISW_ARG((ab), IswNrowSpacing, (v))
#define IswSetVerticalList(ab, v)               ISW_ARG((ab), IswNverticalList, (v))
#define IswSetDropdownMode(ab, v)               ISW_ARG((ab), IswNdropdownMode, (v))

/* Scrollbar */
#define IswSetMinimumThumb(ab, v)               ISW_ARG((ab), IswNminimumThumb, (v))
#define IswSetTopOfThumb(ab, v)                 ISW_ARG((ab), IswNtopOfThumb, (v))
#define IswSetPickTop(ab, v)                    ISW_ARG((ab), IswNpickTop, (v))
#define IswSetScrollWheelIncrement(ab, v)       ISW_ARG((ab), IswNscrollWheelIncrement, (v))

/* Slider */
#define IswSetMinimumValue(ab, v)               ISW_ARG((ab), IswNminimumValue, (v))
#define IswSetMaximumValue(ab, v)               ISW_ARG((ab), IswNmaximumValue, (v))
#define IswSetSliderValue(ab, v)                ISW_ARG((ab), IswNsliderValue, (v))
#define IswSetShowValue(ab, v)                  ISW_ARG((ab), IswNshowValue, (v))
#define IswSetValueChanged(ab, v)               ISW_ARG((ab), IswNvalueChanged, (v))
#define IswSetValuePosition(ab, v)              ISW_ARG((ab), IswNvaluePosition, (v))
#define IswSetTickInterval(ab, v)               ISW_ARG((ab), IswNtickInterval, (v))

/* SpinBox */
#define IswSetSpinMinimum(ab, v)                ISW_ARG((ab), IswNspinMinimum, (v))
#define IswSetSpinMaximum(ab, v)                ISW_ARG((ab), IswNspinMaximum, (v))
#define IswSetSpinValue(ab, v)                  ISW_ARG((ab), IswNspinValue, (v))
#define IswSetSpinIncrement(ab, v)              ISW_ARG((ab), IswNspinIncrement, (v))
#define IswSetSpinWrap(ab, v)                   ISW_ARG((ab), IswNspinWrap, (v))

/* ColorPicker */
#define IswSetColorRed(ab, v)                   ISW_ARG((ab), IswNcolorRed, (v))
#define IswSetColorGreen(ab, v)                 ISW_ARG((ab), IswNcolorGreen, (v))
#define IswSetColorBlue(ab, v)                  ISW_ARG((ab), IswNcolorBlue, (v))
#define IswSetColorChanged(ab, v)               ISW_ARG((ab), IswNcolorChanged, (v))

/* FontChooser */
#define IswSetFontFamily(ab, v)                 ISW_ARG((ab), IswNfontFamily, (v))
#define IswSetFontSize(ab, v)                   ISW_ARG((ab), IswNfontSize, (v))
#define IswSetFontWeight(ab, v)                 ISW_ARG((ab), IswNfontWeight, (v))
#define IswSetFontSlant(ab, v)                  ISW_ARG((ab), IswNfontSlant, (v))
#define IswSetPreviewText(ab, v)                ISW_ARG((ab), IswNpreviewText, (v))
#define IswSetFontChanged(ab, v)                ISW_ARG((ab), IswNfontChanged, (v))

/* FlexBox */
#define IswSetSpacing(ab, v)                    ISW_ARG((ab), IswNspacing, (v))
#define IswSetFlexGrow(ab, v)                   ISW_ARG((ab), IswNflexGrow, (v))
#define IswSetFlexBasis(ab, v)                  ISW_ARG((ab), IswNflexBasis, (v))
#define IswSetFlexAlign(ab, v)                  ISW_ARG((ab), IswNflexAlign, (v))

/* Tree */
#define IswSetAutoReconfigure(ab, v)            ISW_ARG((ab), IswNautoReconfigure, (v))
#define IswSetTreeForeground(ab, v)             ISW_ARG((ab), IswNtreeForeground, (v))
#define IswSetTreeParent(ab, v)                 ISW_ARG((ab), IswNtreeParent, (v))
#define IswSetGravity(ab, v)                    ISW_ARG((ab), IswNgravity, (v))

/* IconView */
#define IswSetIconLabels(ab, v)                 ISW_ARG((ab), IswNiconLabels, (v))
#define IswSetIconData(ab, v)                   ISW_ARG((ab), IswNiconData, (v))
#define IswSetNumIcons(ab, v)                   ISW_ARG((ab), IswNnumIcons, (v))
#define IswSetIconSize(ab, v)                   ISW_ARG((ab), IswNiconSize, (v))
#define IswSetItemSpacing(ab, v)                ISW_ARG((ab), IswNitemSpacing, (v))
#define IswSetLabelLines(ab, v)                 ISW_ARG((ab), IswNlabelLines, (v))
#define IswSetSelectCallback(ab, v)             ISW_ARG((ab), IswNselectCallback, (v))
#define IswSetMultiSelect(ab, v)                ISW_ARG((ab), IswNmultiSelect, (v))
#define IswSetCursorItem(ab, v)                 ISW_ARG((ab), IswNcursorItem, (v))

/* ListView */
#define IswSetListViewColumns(ab, v)            ISW_ARG((ab), IswNlistViewColumns, (v))
#define IswSetNumColumns(ab, v)                 ISW_ARG((ab), IswNnumColumns, (v))
#define IswSetNumRows(ab, v)                    ISW_ARG((ab), IswNnumRows, (v))
#define IswSetListViewData(ab, v)               ISW_ARG((ab), IswNlistViewData, (v))
#define IswSetRowHeight(ab, v)                  ISW_ARG((ab), IswNrowHeight, (v))
#define IswSetHeaderHeight(ab, v)               ISW_ARG((ab), IswNheaderHeight, (v))
#define IswSetCursorRow(ab, v)                  ISW_ARG((ab), IswNcursorRow, (v))
#define IswSetShowHeader(ab, v)                 ISW_ARG((ab), IswNshowHeader, (v))
#define IswSetReorderCallback(ab, v)            ISW_ARG((ab), IswNreorderCallback, (v))

/* Command */
#define IswSetBorderStrokeWidth(ab, v)          ISW_ARG((ab), IswNborderStrokeWidth, (v))
#define IswSetHighlightThickness(ab, v)         ISW_ARG((ab), IswNhighlightThickness, (v))
#define IswSetShapeStyle(ab, v)                 ISW_ARG((ab), IswNshapeStyle, (v))
#define IswSetCornerRadius(ab, v)               ISW_ARG((ab), IswNcornerRadius, (v))

/* Toggle */
#define IswSetState(ab, v)                      ISW_ARG((ab), IswNstate, (v))
#define IswSetRadioGroup(ab, v)                 ISW_ARG((ab), IswNradioGroup, (v))
#define IswSetRadioData(ab, v)                  ISW_ARG((ab), IswNradioData, (v))

/* Tabs */
#define IswSetTabCallback(ab, v)                ISW_ARG((ab), IswNtabCallback, (v))
#define IswSetTopWidget(ab, v)                  ISW_ARG((ab), IswNtopWidget, (v))
#define IswSetTabLabel(ab, v)                   ISW_ARG((ab), IswNtabLabel, (v))

/* Repeater */
#define IswSetDecay(ab, v)                      ISW_ARG((ab), IswNdecay, (v))
#define IswSetInitialDelay(ab, v)               ISW_ARG((ab), IswNinitialDelay, (v))
#define IswSetMinimumDelay(ab, v)               ISW_ARG((ab), IswNminimumDelay, (v))
#define IswSetRepeatDelay(ab, v)                ISW_ARG((ab), IswNrepeatDelay, (v))
#define IswSetFlash(ab, v)                      ISW_ARG((ab), IswNflash, (v))
#define IswSetStartCallback(ab, v)              ISW_ARG((ab), IswNstartCallback, (v))
#define IswSetStopCallback(ab, v)               ISW_ARG((ab), IswNstopCallback, (v))

/* StatusBar / Toolbar / MenuButton */
#define IswSetStatusStretch(ab, v)              ISW_ARG((ab), IswNstatusStretch, (v))
#define IswSetToolbarAlignment(ab, v)           ISW_ARG((ab), IswNtoolbarAlignment, (v))
#define IswSetMenuName(ab, v)                   ISW_ARG((ab), IswNmenuName, (v))

/* SimpleMenu */
#define IswSetColumnWidth(ab, v)                ISW_ARG((ab), IswNcolumnWidth, (v))
#define IswSetLabelClass(ab, v)                 ISW_ARG((ab), IswNlabelClass, (v))
#define IswSetMenuOnScreen(ab, v)               ISW_ARG((ab), IswNmenuOnScreen, (v))
#define IswSetPopupOnEntry(ab, v)               ISW_ARG((ab), IswNpopupOnEntry, (v))

/* Simple */
#define IswSetCursorName(ab, v)                 ISW_ARG((ab), IswNcursorName, (v))
#define IswSetInsensitiveBorder(ab, v)          ISW_ARG((ab), IswNinsensitiveBorder, (v))
#define IswSetInternational(ab, v)              ISW_ARG((ab), IswNinternational, (v))

/* Label */
#define IswSetImage(ab, v)                      ISW_ARG((ab), IswNimage, (v))
#define IswSetLeftImage(ab, v)                  ISW_ARG((ab), IswNleftImage, (v))
#define IswSetEncoding(ab, v)                   ISW_ARG((ab), IswNencoding, (v))

/* Tip */
#define IswSetTimeout(ab, v)                    ISW_ARG((ab), IswNtimeout, (v))
#define IswSetTip(ab, v)                        ISW_ARG((ab), IswNtip, (v))

/* DrawingArea */
#define IswSetExposeCallback(ab, v)             ISW_ARG((ab), IswNexposeCallback, (v))
#define IswSetResizeCallback(ab, v)             ISW_ARG((ab), IswNresizeCallback, (v))
#define IswSetInputCallback(ab, v)              ISW_ARG((ab), IswNinputCallback, (v))

/* Dialog / Layout / Template / Reports / ProgressBar / Grip */
#define IswSetIcon(ab, v)                       ISW_ARG((ab), IswNicon, (v))
#define IswSetLayout(ab, v)                     ISW_ARG((ab), IswNlayout, (v))
#define IswSetDebug(ab, v)                      ISW_ARG((ab), IswNdebug, (v))
#define IswSetTemplateResource(ab, v)           ISW_ARG((ab), IswNtemplateResource, (v))
#define IswSetReportCallback(ab, v)             ISW_ARG((ab), IswNreportCallback, (v))
#define IswSetGripTranslations(ab, v)           ISW_ARG((ab), IswNgripTranslations, (v))

/* AsciiSrc / MultiSrc */
#define IswSetDataCompression(ab, v)            ISW_ARG((ab), IswNdataCompression, (v))
#define IswSetPieceSize(ab, v)                  ISW_ARG((ab), IswNpieceSize, (v))
#define IswSetType(ab, v)                       ISW_ARG((ab), IswNtype, (v))
#define IswSetUseStringInPlace(ab, v)           ISW_ARG((ab), IswNuseStringInPlace, (v))

/* AsciiSink / MultiSink */
#define IswSetDisplayNonprinting(ab, v)         ISW_ARG((ab), IswNdisplayNonprinting, (v))
#define IswSetEcho(ab, v)                       ISW_ARG((ab), IswNecho, (v))

/* ISWImP */
#define IswSetInputMethod(ab, v)                ISW_ARG((ab), IswNinputMethod, (v))
#define IswSetPreeditType(ab, v)                ISW_ARG((ab), IswNpreeditType, (v))
#define IswSetOpenIm(ab, v)                     ISW_ARG((ab), IswNopenIm, (v))
#define IswSetSharedIc(ab, v)                   ISW_ARG((ab), IswNsharedIc, (v))

/* ISWXdnd */
#define IswSetDropCallback(ab, v)               ISW_ARG((ab), IswNdropCallback, (v))
#define IswSetDragEnterCallback(ab, v)          ISW_ARG((ab), IswNdragEnterCallback, (v))
#define IswSetDragMotionCallback(ab, v)         ISW_ARG((ab), IswNdragMotionCallback, (v))
#define IswSetDragLeaveCallback(ab, v)          ISW_ARG((ab), IswNdragLeaveCallback, (v))

#endif /* _IswArgMacros_h */
