/***********************************************************

Copyright 1987, 1988, 1994, 1998  The Open Group

Permission to use, copy, modify, distribute, and sell this software and its
documentation for any purpose is hereby granted without fee, provided that
the above copyright notice appear in all copies and that both that
copyright notice and this permission notice appear in supporting
documentation.

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
OPEN GROUP BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

Except as contained in this notice, the name of The Open Group shall not be
used in advertising or otherwise to promote the sale, use or other dealings
in this Software without prior written authorization from The Open Group.


Copyright 1987, 1988 by Digital Equipment Corporation, Maynard, Massachusetts.

                        All Rights Reserved

Permission to use, copy, modify, and distribute this software and its
documentation for any purpose and without fee is hereby granted,
provided that the above copyright notice appear in all copies and that
both that copyright notice and this permission notice appear in
supporting documentation, and that the name of Digital not be
used in advertising or publicity pertaining to distribution of the
software without specific, written prior permission.

DIGITAL DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING
ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT SHALL
DIGITAL BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR
ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS
SOFTWARE.

******************************************************************/

#ifndef _IswShell_h
#define _IswShell_h

#include <ISW/Intrinsic.h>

/***********************************************************************
 *
 * Shell Widget
 *
 ***********************************************************************/
/*
 * Shell-specific resources names, classes, and a representation type.
 */

#ifndef ISWSTRINGDEFINES
#define _IswShell_h_Const const
#endif

/* $Xorg: makestrs.c,v 1.6 2001/02/09 02:03:17 xorgcvs Exp $ */
/* This file is automatically generated. */
/* Default ABI version -- Do not edit */
#ifdef ISWSTRINGDEFINES
#define IswNiconName "iconName"
#define IswCIconName "IconName"
#define IswNiconPixmap "iconPixmap"
#define IswCIconPixmap "IconPixmap"
#define IswNiconWindow "iconWindow"
#define IswCIconWindow "IconWindow"
#define IswNiconMask "iconMask"
#define IswCIconMask "IconMask"
#define IswNwindowGroup "windowGroup"
#define IswCWindowGroup "WindowGroup"
#define IswNvisual "visual"
#define IswCVisual "Visual"
#define IswNtitleEncoding "titleEncoding"
#define IswCTitleEncoding "TitleEncoding"
#define IswNsaveUnder "saveUnder"
#define IswCSaveUnder "SaveUnder"
#define IswNtransient "transient"
#define IswCTransient "Transient"
#define IswNoverrideRedirect "overrideRedirect"
#define IswCOverrideRedirect "OverrideRedirect"
#define IswNtransientFor "transientFor"
#define IswCTransientFor "TransientFor"
#define IswNiconNameEncoding "iconNameEncoding"
#define IswCIconNameEncoding "IconNameEncoding"
#define IswNallowShellResize "allowShellResize"
#define IswCAllowShellResize "AllowShellResize"
#define IswNcreatePopupChildProc "createPopupChildProc"
#define IswCCreatePopupChildProc "CreatePopupChildProc"
#define IswNtitle "title"
#define IswCTitle "Title"
#ifndef IswRAtom
#define IswRAtom "Atom"
#endif
#define IswNargc "argc"
#define IswCArgc "Argc"
#define IswNargv "argv"
#define IswCArgv "Argv"
#define IswNiconX "iconX"
#define IswCIconX "IconX"
#define IswNiconY "iconY"
#define IswCIconY "IconY"
#define IswNinput "input"
#define IswCInput "Input"
#define IswNiconic "iconic"
#define IswCIconic "Iconic"
#define IswNinitialState "initialState"
#define IswCInitialState "InitialState"
#define IswNgeometry "geometry"
#define IswCGeometry "Geometry"
#define IswNbaseWidth "baseWidth"
#define IswCBaseWidth "BaseWidth"
#define IswNbaseHeight "baseHeight"
#define IswCBaseHeight "BaseHeight"
#define IswNwinGravity "winGravity"
#define IswCWinGravity "WinGravity"
#define IswNminWidth "minWidth"
#define IswCMinWidth "MinWidth"
#define IswNminHeight "minHeight"
#define IswCMinHeight "MinHeight"
#define IswNmaxWidth "maxWidth"
#define IswCMaxWidth "MaxWidth"
#define IswNmaxHeight "maxHeight"
#define IswCMaxHeight "MaxHeight"
#define IswNwidthInc "widthInc"
#define IswCWidthInc "WidthInc"
#define IswNheightInc "heightInc"
#define IswCHeightInc "HeightInc"
#define IswNminAspectY "minAspectY"
#define IswCMinAspectY "MinAspectY"
#define IswNmaxAspectY "maxAspectY"
#define IswCMaxAspectY "MaxAspectY"
#define IswNminAspectX "minAspectX"
#define IswCMinAspectX "MinAspectX"
#define IswNmaxAspectX "maxAspectX"
#define IswCMaxAspectX "MaxAspectX"
#define IswNwmTimeout "wmTimeout"
#define IswCWmTimeout "WmTimeout"
#define IswNwaitForWm "waitforwm"
#define IswCWaitForWm "Waitforwm"
#define IswNwaitforwm "waitforwm"
#define IswCWaitforwm "Waitforwm"
#define IswNclientLeader "clientLeader"
#define IswCClientLeader "ClientLeader"
#define IswNwindowRole "windowRole"
#define IswCWindowRole "WindowRole"
#define IswNurgency "urgency"
#define IswCUrgency "Urgency"
#define IswNbottom "bottom"
#define IswNleft "left"
#define IswNright "right"
#else
extern _IswShell_h_Const char IswShellStrings[];
#ifndef IswNiconName
#define IswNiconName ((String)&IswShellStrings[0])
#endif
#ifndef IswCIconName
#define IswCIconName ((String)&IswShellStrings[9])
#endif
#ifndef IswNiconPixmap
#define IswNiconPixmap ((String)&IswShellStrings[18])
#endif
#ifndef IswCIconPixmap
#define IswCIconPixmap ((String)&IswShellStrings[29])
#endif
#ifndef IswNiconWindow
#define IswNiconWindow ((String)&IswShellStrings[40])
#endif
#ifndef IswCIconWindow
#define IswCIconWindow ((String)&IswShellStrings[51])
#endif
#ifndef IswNiconMask
#define IswNiconMask ((String)&IswShellStrings[62])
#endif
#ifndef IswCIconMask
#define IswCIconMask ((String)&IswShellStrings[71])
#endif
#ifndef IswNwindowGroup
#define IswNwindowGroup ((String)&IswShellStrings[80])
#endif
#ifndef IswCWindowGroup
#define IswCWindowGroup ((String)&IswShellStrings[92])
#endif
#ifndef IswNvisual
#define IswNvisual ((String)&IswShellStrings[104])
#endif
#ifndef IswCVisual
#define IswCVisual ((String)&IswShellStrings[111])
#endif
#ifndef IswNtitleEncoding
#define IswNtitleEncoding ((String)&IswShellStrings[118])
#endif
#ifndef IswCTitleEncoding
#define IswCTitleEncoding ((String)&IswShellStrings[132])
#endif
#ifndef IswNsaveUnder
#define IswNsaveUnder ((String)&IswShellStrings[146])
#endif
#ifndef IswCSaveUnder
#define IswCSaveUnder ((String)&IswShellStrings[156])
#endif
#ifndef IswNtransient
#define IswNtransient ((String)&IswShellStrings[166])
#endif
#ifndef IswCTransient
#define IswCTransient ((String)&IswShellStrings[176])
#endif
#ifndef IswNoverrideRedirect
#define IswNoverrideRedirect ((String)&IswShellStrings[186])
#endif
#ifndef IswCOverrideRedirect
#define IswCOverrideRedirect ((String)&IswShellStrings[203])
#endif
#ifndef IswNtransientFor
#define IswNtransientFor ((String)&IswShellStrings[220])
#endif
#ifndef IswCTransientFor
#define IswCTransientFor ((String)&IswShellStrings[233])
#endif
#ifndef IswNiconNameEncoding
#define IswNiconNameEncoding ((String)&IswShellStrings[246])
#endif
#ifndef IswCIconNameEncoding
#define IswCIconNameEncoding ((String)&IswShellStrings[263])
#endif
#ifndef IswNallowShellResize
#define IswNallowShellResize ((String)&IswShellStrings[280])
#endif
#ifndef IswCAllowShellResize
#define IswCAllowShellResize ((String)&IswShellStrings[297])
#endif
#ifndef IswNcreatePopupChildProc
#define IswNcreatePopupChildProc ((String)&IswShellStrings[314])
#endif
#ifndef IswCCreatePopupChildProc
#define IswCCreatePopupChildProc ((String)&IswShellStrings[335])
#endif
#ifndef IswNtitle
#define IswNtitle ((String)&IswShellStrings[356])
#endif
#ifndef IswCTitle
#define IswCTitle ((String)&IswShellStrings[362])
#endif
#ifndef IswRAtom
#define IswRAtom ((String)&IswShellStrings[368])
#endif
#ifndef IswNargc
#define IswNargc ((String)&IswShellStrings[373])
#endif
#ifndef IswCArgc
#define IswCArgc ((String)&IswShellStrings[378])
#endif
#ifndef IswNargv
#define IswNargv ((String)&IswShellStrings[383])
#endif
#ifndef IswCArgv
#define IswCArgv ((String)&IswShellStrings[388])
#endif
#ifndef IswNiconX
#define IswNiconX ((String)&IswShellStrings[393])
#endif
#ifndef IswCIconX
#define IswCIconX ((String)&IswShellStrings[399])
#endif
#ifndef IswNiconY
#define IswNiconY ((String)&IswShellStrings[405])
#endif
#ifndef IswCIconY
#define IswCIconY ((String)&IswShellStrings[411])
#endif
#ifndef IswNinput
#define IswNinput ((String)&IswShellStrings[417])
#endif
#ifndef IswCInput
#define IswCInput ((String)&IswShellStrings[423])
#endif
#ifndef IswNiconic
#define IswNiconic ((String)&IswShellStrings[429])
#endif
#ifndef IswCIconic
#define IswCIconic ((String)&IswShellStrings[436])
#endif
#ifndef IswNinitialState
#define IswNinitialState ((String)&IswShellStrings[443])
#endif
#ifndef IswCInitialState
#define IswCInitialState ((String)&IswShellStrings[456])
#endif
#ifndef IswNgeometry
#define IswNgeometry ((String)&IswShellStrings[469])
#endif
#ifndef IswCGeometry
#define IswCGeometry ((String)&IswShellStrings[478])
#endif
#ifndef IswNbaseWidth
#define IswNbaseWidth ((String)&IswShellStrings[487])
#endif
#ifndef IswCBaseWidth
#define IswCBaseWidth ((String)&IswShellStrings[497])
#endif
#ifndef IswNbaseHeight
#define IswNbaseHeight ((String)&IswShellStrings[507])
#endif
#ifndef IswCBaseHeight
#define IswCBaseHeight ((String)&IswShellStrings[518])
#endif
#ifndef IswNwinGravity
#define IswNwinGravity ((String)&IswShellStrings[529])
#endif
#ifndef IswCWinGravity
#define IswCWinGravity ((String)&IswShellStrings[540])
#endif
#ifndef IswNminWidth
#define IswNminWidth ((String)&IswShellStrings[551])
#endif
#ifndef IswCMinWidth
#define IswCMinWidth ((String)&IswShellStrings[560])
#endif
#ifndef IswNminHeight
#define IswNminHeight ((String)&IswShellStrings[569])
#endif
#ifndef IswCMinHeight
#define IswCMinHeight ((String)&IswShellStrings[579])
#endif
#ifndef IswNmaxWidth
#define IswNmaxWidth ((String)&IswShellStrings[589])
#endif
#ifndef IswCMaxWidth
#define IswCMaxWidth ((String)&IswShellStrings[598])
#endif
#ifndef IswNmaxHeight
#define IswNmaxHeight ((String)&IswShellStrings[607])
#endif
#ifndef IswCMaxHeight
#define IswCMaxHeight ((String)&IswShellStrings[617])
#endif
#ifndef IswNwidthInc
#define IswNwidthInc ((String)&IswShellStrings[627])
#endif
#ifndef IswCWidthInc
#define IswCWidthInc ((String)&IswShellStrings[636])
#endif
#ifndef IswNheightInc
#define IswNheightInc ((String)&IswShellStrings[645])
#endif
#ifndef IswCHeightInc
#define IswCHeightInc ((String)&IswShellStrings[655])
#endif
#ifndef IswNminAspectY
#define IswNminAspectY ((String)&IswShellStrings[665])
#endif
#ifndef IswCMinAspectY
#define IswCMinAspectY ((String)&IswShellStrings[676])
#endif
#ifndef IswNmaxAspectY
#define IswNmaxAspectY ((String)&IswShellStrings[687])
#endif
#ifndef IswCMaxAspectY
#define IswCMaxAspectY ((String)&IswShellStrings[698])
#endif
#ifndef IswNminAspectX
#define IswNminAspectX ((String)&IswShellStrings[709])
#endif
#ifndef IswCMinAspectX
#define IswCMinAspectX ((String)&IswShellStrings[720])
#endif
#ifndef IswNmaxAspectX
#define IswNmaxAspectX ((String)&IswShellStrings[731])
#endif
#ifndef IswCMaxAspectX
#define IswCMaxAspectX ((String)&IswShellStrings[742])
#endif
#ifndef IswNwmTimeout
#define IswNwmTimeout ((String)&IswShellStrings[753])
#endif
#ifndef IswCWmTimeout
#define IswCWmTimeout ((String)&IswShellStrings[763])
#endif
#ifndef IswNwaitForWm
#define IswNwaitForWm ((String)&IswShellStrings[773])
#endif
#ifndef IswCWaitForWm
#define IswCWaitForWm ((String)&IswShellStrings[783])
#endif
#ifndef IswNwaitforwm
#define IswNwaitforwm ((String)&IswShellStrings[793])
#endif
#ifndef IswCWaitforwm
#define IswCWaitforwm ((String)&IswShellStrings[803])
#endif
#ifndef IswNclientLeader
#define IswNclientLeader ((String)&IswShellStrings[813])
#endif
#ifndef IswCClientLeader
#define IswCClientLeader ((String)&IswShellStrings[826])
#endif
#ifndef IswNwindowRole
#define IswNwindowRole ((String)&IswShellStrings[839])
#endif
#ifndef IswCWindowRole
#define IswCWindowRole ((String)&IswShellStrings[850])
#endif
#ifndef IswNurgency
#define IswNurgency ((String)&IswShellStrings[861])
#endif
#ifndef IswCUrgency
#define IswCUrgency ((String)&IswShellStrings[869])
#endif
#ifndef IswNbottom
#define IswNbottom ((String)&IswShellStrings[877])
#endif
#ifndef IswNleft
#define IswNleft ((String)&IswShellStrings[884])
#endif
#ifndef IswNright
#define IswNright ((String)&IswShellStrings[889])
#endif
#endif /* ISWSTRINGDEFINES */

#ifndef ISWSTRINGDEFINES
#undef _IswShell_h_Const
#endif

/* Class record constants */

typedef struct _ShellClassRec *ShellWidgetClass;
typedef struct _OverrideShellClassRec *OverrideShellWidgetClass;
typedef struct _WMShellClassRec *WMShellWidgetClass;
typedef struct _TransientShellClassRec *TransientShellWidgetClass;
typedef struct _TopLevelShellClassRec *TopLevelShellWidgetClass;
typedef struct _ApplicationShellClassRec *ApplicationShellWidgetClass;

#ifndef SHELL
externalref WidgetClass shellWidgetClass;
externalref WidgetClass overrideShellWidgetClass;
externalref WidgetClass wmShellWidgetClass;
externalref WidgetClass transientShellWidgetClass;
externalref WidgetClass topLevelShellWidgetClass;
externalref WidgetClass applicationShellWidgetClass;
#endif

void IswSetWindowIconRGBA(Widget shell, const unsigned char *rgba,
                          unsigned int width, unsigned int height);

void IswSetWindowIconARGB(Widget shell, const uint32_t *argb_data,
                          unsigned int n_entries);

void IswClearWindowIcon(Widget shell);

void IswSetWindowName(Widget shell, const char *name);

void IswSetWindowIconName(Widget shell, const char *name);

void IswSetWindowState(Widget shell, const char *state, Boolean set);

#endif /* _IswShell_h */
/* DON'T ADD STUFF AFTER THIS #endif */
