/***********************************************************

Copyright 1987, 1988, 1994, 1998  The Open Group

Permission to use, copy, modify, distribute, and sell this software and its
documentation for any purpose is hereby granted without fee, provided that
the above copyright notice appear in all copies and that both that
copyright notice and this permission notice appear in supporting
documentation.

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
OPEN GROUP BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

Except as contained in this notice, the name of The Open Group shall not be
used in advertising or otherwise to promote the sale, use or other dealings
in this Software without prior written authorization from The Open Group.


Copyright 1987, 1988 by Digital Equipment Corporation, Maynard, Massachusetts.

                        All Rights Reserved

Permission to use, copy, modify, and distribute this software and its
documentation for any purpose and without fee is hereby granted,
provided that the above copyright notice appear in all copies and that
both that copyright notice and this permission notice appear in
supporting documentation, and that the name of Digital not be
used in advertising or publicity pertaining to distribution of the
software without specific, written prior permission.

DIGITAL DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING
ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT SHALL
DIGITAL BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR
ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS
SOFTWARE.

******************************************************************/

#ifndef _IswStringDefs_h_
#define _IswStringDefs_h_

#ifndef ISWSTRINGDEFINES
#define _IswStringDefs_h_Const const
#endif

/* $Xorg: makestrs.c,v 1.6 2001/02/09 02:03:17 xorgcvs Exp $ */
/* This file is automatically generated. */
/* Default ABI version -- Do not edit */
#ifdef ISWSTRINGDEFINES
#define IswNaccelerators "accelerators"
#define IswNallowHoriz "allowHoriz"
#define IswNallowVert "allowVert"
#define IswNancestorSensitive "ancestorSensitive"
#define IswNbackground "background"
#define IswNbitmap "bitmap"
#define IswNborderColor "borderColor"
#define IswNborder "borderColor"
#define IswNborderWidth "borderWidth"
#define IswNborderTop "borderTop"
#define IswNborderRight "borderRight"
#define IswNborderBottom "borderBottom"
#define IswNborderLeft "borderLeft"
#define IswNcallback "callback"
#define IswNchildren "children"
#define IswNcolormap "colormap"
#define IswNdepth "depth"
#define IswNdestroyCallback "destroyCallback"
#define IswNeditType "editType"
#define IswNfile "file"
#define IswNfont "font"
#define IswNforceBars "forceBars"
#define IswNforeground "foreground"
#define IswNfunction "function"
#define IswNheight "height"
#define IswNhighlight "highlight"
#define IswNhSpace "hSpace"
#define IswNindex "index"
#define IswNinitialResourcesPersistent "initialResourcesPersistent"
#define IswNinnerHeight "innerHeight"
#define IswNinnerWidth "innerWidth"
#define IswNinnerWindow "innerWindow"
#define IswNinsertPosition "insertPosition"
#define IswNinternalHeight "internalHeight"
#define IswNinternalWidth "internalWidth"
#define IswNjumpProc "jumpProc"
#define IswNjustify "justify"
#define IswNknobHeight "knobHeight"
#define IswNknobIndent "knobIndent"
#define IswNknobPixel "knobPixel"
#define IswNknobWidth "knobWidth"
#define IswNlabel "label"
#define IswNlength "length"
#define IswNlowerRight "lowerRight"
#define IswNmappedWhenManaged "mappedWhenManaged"
#define IswNmenuEntry "menuEntry"
#define IswNname "name"
#define IswNnotify "notify"
#define IswNnumChildren "numChildren"
#define IswNorientation "orientation"
#define IswNparameter "parameter"
#define IswNpixmap "pixmap"
#define IswNpopupCallback "popupCallback"
#define IswNpopdownCallback "popdownCallback"
#define IswNresize "resize"
#define IswNreverseVideo "reverseVideo"
#define IswNscreen "screen"
#define IswNscrollProc "scrollProc"
#define IswNscrollDCursor "scrollDCursor"
#define IswNscrollHCursor "scrollHCursor"
#define IswNscrollLCursor "scrollLCursor"
#define IswNscrollRCursor "scrollRCursor"
#define IswNscrollUCursor "scrollUCursor"
#define IswNscrollVCursor "scrollVCursor"
#define IswNselection "selection"
#define IswNselectionArray "selectionArray"
#define IswNsensitive "sensitive"
#define IswNshown "shown"
#define IswNspace "space"
#define IswNstring "string"
#define IswNtextOptions "textOptions"
#define IswNtextSink "textSink"
#define IswNtextSource "textSource"
#define IswNthickness "thickness"
#define IswNthumbProc "thumbProc"
#define IswNtop "top"
#define IswNtranslations "translations"
#define IswNunrealizeCallback "unrealizeCallback"
#define IswNupdate "update"
#define IswNuseBottom "useBottom"
#define IswNuseRight "useRight"
#define IswNvalue "value"
#define IswNvSpace "vSpace"
#define IswNwidth "width"
#define IswNwindow "window"
#define IswNx "x"
#define IswNy "y"
#define IswCAccelerators "Accelerators"
#define IswCBackground "Background"
#define IswCBitmap "Bitmap"
#define IswCBoolean "Boolean"
#define IswCBorderColor "BorderColor"
#define IswCBorderWidth "BorderWidth"
#define IswCCallback "Callback"
#define IswCColormap "Colormap"
#define IswCColor "Color"
#define IswCCursor "Cursor"
#define IswCDepth "Depth"
#define IswCEditType "EditType"
#define IswCEventBindings "EventBindings"
#define IswCFile "File"
#define IswCFont "Font"
#define IswCForeground "Foreground"
#define IswCFraction "Fraction"
#define IswCFunction "Function"
#define IswCHeight "Height"
#define IswCHSpace "HSpace"
#define IswCIndex "Index"
#define IswCInitialResourcesPersistent "InitialResourcesPersistent"
#define IswCInsertPosition "InsertPosition"
#define IswCInterval "Interval"
#define IswCJustify "Justify"
#define IswCKnobIndent "KnobIndent"
#define IswCKnobPixel "KnobPixel"
#define IswCLabel "Label"
#define IswCLength "Length"
#define IswCMappedWhenManaged "MappedWhenManaged"
#define IswCMargin "Margin"
#define IswCMenuEntry "MenuEntry"
#define IswCNotify "Notify"
#define IswCOrientation "Orientation"
#define IswCParameter "Parameter"
#define IswCPixmap "Pixmap"
#define IswCPosition "Position"
#define IswCReadOnly "ReadOnly"
#define IswCResize "Resize"
#define IswCReverseVideo "ReverseVideo"
#define IswCScreen "Screen"
#define IswCScrollProc "ScrollProc"
#define IswCScrollDCursor "ScrollDCursor"
#define IswCScrollHCursor "ScrollHCursor"
#define IswCScrollLCursor "ScrollLCursor"
#define IswCScrollRCursor "ScrollRCursor"
#define IswCScrollUCursor "ScrollUCursor"
#define IswCScrollVCursor "ScrollVCursor"
#define IswCSelection "Selection"
#define IswCSensitive "Sensitive"
#define IswCSelectionArray "SelectionArray"
#define IswCSpace "Space"
#define IswCString "String"
#define IswCTextOptions "TextOptions"
#define IswCTextPosition "TextPosition"
#define IswCTextSink "TextSink"
#define IswCTextSource "TextSource"
#define IswCThickness "Thickness"
#define IswCTranslations "Translations"
#define IswCValue "Value"
#define IswCVSpace "VSpace"
#define IswCWidth "Width"
#define IswCWindow "Window"
#define IswCX "X"
#define IswCY "Y"
#define IswRAcceleratorTable "AcceleratorTable"
#ifndef IswRAtom
#define IswRAtom "Atom"
#endif
#define IswRBitmap "Bitmap"
#define IswRBool "Bool"
#define IswRBoolean "Boolean"
#define IswRCallback "Callback"
#define IswRCallProc "CallProc"
#define IswRCardinal "Cardinal"
#define IswRColor "Color"
#define IswRColormap "Colormap"
#define IswRCursor "Cursor"
#define IswRDimension "Dimension"
#define IswRDisplay "Display"
#define IswREditMode "EditMode"
#define IswREnum "Enum"
#define IswRFile "File"
#define IswRFloat "Float"
#define IswRFont "Font"
#define IswRFontStruct "FontStruct"
#define IswRFunction "Function"
#define IswRGeometry "Geometry"
#define IswRImmediate "Immediate"
#define IswRInitialState "InitialState"
#define IswRInt "Int"
#define IswRJustify "Justify"
#define IswRLongBoolean "Bool"
#define IswRObject "Object"
#define IswROrientation "Orientation"
#define IswRPixel "Pixel"
#define IswRPixmap "Pixmap"
#define IswRPointer "Pointer"
#define IswRPosition "Position"
#define IswRScreen "Screen"
#define IswRShort "Short"
#define IswRString "String"
#define IswRStringArray "StringArray"
#define IswRStringTable "StringTable"
#define IswRUnsignedChar "UnsignedChar"
#define IswRTranslationTable "TranslationTable"
#define IswRVisual "Visual"
#define IswRWidget "Widget"
#define IswRWidgetClass "WidgetClass"
#define IswRWidgetList "WidgetList"
#define IswRWindow "Window"
#define IswRWindowType "WindowType"
#define IswEoff "off"
#define IswEfalse "false"
#define IswEno "no"
#define IswEon "on"
#define IswEtrue "true"
#define IswEyes "yes"
#define IswEvertical "vertical"
#define IswEhorizontal "horizontal"
#define IswEtextRead "read"
#define IswEtextAppend "append"
#define IswEtextEdit "edit"
#define IswExtdefaultbackground "xtdefaultbackground"
#define IswExtdefaultforeground "xtdefaultforeground"
#define IswExtdefaultfont "xtdefaultfont"
#define IswNfontSet "fontSet"
#define IswRFontSet "FontSet"
#define IswCFontSet "FontSet"
#define IswRGravity "Gravity"
#define IswNcreateHook "createHook"
#define IswNchangeHook "changeHook"
#define IswNconfigureHook "configureHook"
#define IswNgeometryHook "geometryHook"
#define IswNdestroyHook "destroyHook"
#define IswNshells "shells"
#define IswNnumShells "numShells"
#define IswHcreate "Iswcreate"
#define IswHsetValues "IswsetValues"
#define IswHmanageChildren "IswmanageChildren"
#define IswHunmanageChildren "IswunmanageChildren"
#define IswHmanageSet "IswmanageSet"
#define IswHunmanageSet "IswunmanageSet"
#define IswHrealizeWidget "IswrealizeWidget"
#define IswHunrealizeWidget "IswunrealizeWidget"
#define IswHaddCallback "IswaddCallback"
#define IswHaddCallbacks "IswaddCallbacks"
#define IswHremoveCallback "IswremoveCallback"
#define IswHremoveCallbacks "IswremoveCallbacks"
#define IswHremoveAllCallbacks "IswremoveAllCallbacks"
#define IswHaugmentTranslations "IswaugmentTranslations"
#define IswHoverrideTranslations "IswoverrideTranslations"
#define IswHuninstallTranslations "IswuninstallTranslations"
#define IswHsetKeyboardFocus "IswsetKeyboardFocus"
#define IswHsetWMColormapWindows "IswsetWMColormapWindows"
#define IswHsetMappedWhenManaged "IswsetMappedWhenManaged"
#define IswHmapWidget "IswmapWidget"
#define IswHunmapWidget "IswunmapWidget"
#define IswHpopup "Iswpopup"
#define IswHpopdown "Iswpopdown"
#define IswHconfigure "Iswconfigure"
#define IswHpreGeometry "IswpreGeometry"
#define IswHpostGeometry "IswpostGeometry"
#define IswHdestroy "Iswdestroy"
#define IswNtraversalOn "traversalOn"
#define IswCTraversalOn "TraversalOn"
#define IswNtabIndex "tabIndex"
#define IswCTabIndex "TabIndex"
#define IswNconsumeTab "consumeTab"
#define IswCConsumeTab "ConsumeTab"
#define IswNmnemonicKey "mnemonicKey"
#define IswCMnemonicKey "MnemonicKey"
#else
extern _IswStringDefs_h_Const char IswStrings[];
#ifndef IswNaccelerators
#define IswNaccelerators ((String)&IswStrings[0])
#endif
#ifndef IswNallowHoriz
#define IswNallowHoriz ((String)&IswStrings[13])
#endif
#ifndef IswNallowVert
#define IswNallowVert ((String)&IswStrings[24])
#endif
#ifndef IswNancestorSensitive
#define IswNancestorSensitive ((String)&IswStrings[34])
#endif
#ifndef IswNbackground
#define IswNbackground ((String)&IswStrings[52])
#endif
#ifndef IswNbitmap
#define IswNbitmap ((String)&IswStrings[63])
#endif
#ifndef IswNborderColor
#define IswNborderColor ((String)&IswStrings[70])
#endif
#ifndef IswNborder
#define IswNborder ((String)&IswStrings[82])
#endif
#ifndef IswNborderWidth
#define IswNborderWidth ((String)&IswStrings[94])
#endif
#ifndef IswNcallback
#define IswNcallback ((String)&IswStrings[106])
#endif
#ifndef IswNchildren
#define IswNchildren ((String)&IswStrings[115])
#endif
#ifndef IswNcolormap
#define IswNcolormap ((String)&IswStrings[124])
#endif
#ifndef IswNdepth
#define IswNdepth ((String)&IswStrings[133])
#endif
#ifndef IswNdestroyCallback
#define IswNdestroyCallback ((String)&IswStrings[139])
#endif
#ifndef IswNeditType
#define IswNeditType ((String)&IswStrings[155])
#endif
#ifndef IswNfile
#define IswNfile ((String)&IswStrings[164])
#endif
#ifndef IswNfont
#define IswNfont ((String)&IswStrings[169])
#endif
#ifndef IswNforceBars
#define IswNforceBars ((String)&IswStrings[174])
#endif
#ifndef IswNforeground
#define IswNforeground ((String)&IswStrings[184])
#endif
#ifndef IswNfunction
#define IswNfunction ((String)&IswStrings[195])
#endif
#ifndef IswNheight
#define IswNheight ((String)&IswStrings[204])
#endif
#ifndef IswNhighlight
#define IswNhighlight ((String)&IswStrings[211])
#endif
#ifndef IswNhSpace
#define IswNhSpace ((String)&IswStrings[221])
#endif
#ifndef IswNindex
#define IswNindex ((String)&IswStrings[228])
#endif
#ifndef IswNinitialResourcesPersistent
#define IswNinitialResourcesPersistent ((String)&IswStrings[234])
#endif
#ifndef IswNinnerHeight
#define IswNinnerHeight ((String)&IswStrings[261])
#endif
#ifndef IswNinnerWidth
#define IswNinnerWidth ((String)&IswStrings[273])
#endif
#ifndef IswNinnerWindow
#define IswNinnerWindow ((String)&IswStrings[284])
#endif
#ifndef IswNinsertPosition
#define IswNinsertPosition ((String)&IswStrings[296])
#endif
#ifndef IswNinternalHeight
#define IswNinternalHeight ((String)&IswStrings[311])
#endif
#ifndef IswNinternalWidth
#define IswNinternalWidth ((String)&IswStrings[326])
#endif
#ifndef IswNjumpProc
#define IswNjumpProc ((String)&IswStrings[340])
#endif
#ifndef IswNjustify
#define IswNjustify ((String)&IswStrings[349])
#endif
#ifndef IswNknobHeight
#define IswNknobHeight ((String)&IswStrings[357])
#endif
#ifndef IswNknobIndent
#define IswNknobIndent ((String)&IswStrings[368])
#endif
#ifndef IswNknobPixel
#define IswNknobPixel ((String)&IswStrings[379])
#endif
#ifndef IswNknobWidth
#define IswNknobWidth ((String)&IswStrings[389])
#endif
#ifndef IswNlabel
#define IswNlabel ((String)&IswStrings[399])
#endif
#ifndef IswNlength
#define IswNlength ((String)&IswStrings[405])
#endif
#ifndef IswNlowerRight
#define IswNlowerRight ((String)&IswStrings[412])
#endif
#ifndef IswNmappedWhenManaged
#define IswNmappedWhenManaged ((String)&IswStrings[423])
#endif
#ifndef IswNmenuEntry
#define IswNmenuEntry ((String)&IswStrings[441])
#endif
#ifndef IswNname
#define IswNname ((String)&IswStrings[451])
#endif
#ifndef IswNnotify
#define IswNnotify ((String)&IswStrings[456])
#endif
#ifndef IswNnumChildren
#define IswNnumChildren ((String)&IswStrings[463])
#endif
#ifndef IswNorientation
#define IswNorientation ((String)&IswStrings[475])
#endif
#ifndef IswNparameter
#define IswNparameter ((String)&IswStrings[487])
#endif
#ifndef IswNpixmap
#define IswNpixmap ((String)&IswStrings[497])
#endif
#ifndef IswNpopupCallback
#define IswNpopupCallback ((String)&IswStrings[504])
#endif
#ifndef IswNpopdownCallback
#define IswNpopdownCallback ((String)&IswStrings[518])
#endif
#ifndef IswNresize
#define IswNresize ((String)&IswStrings[534])
#endif
#ifndef IswNreverseVideo
#define IswNreverseVideo ((String)&IswStrings[541])
#endif
#ifndef IswNscreen
#define IswNscreen ((String)&IswStrings[554])
#endif
#ifndef IswNscrollProc
#define IswNscrollProc ((String)&IswStrings[561])
#endif
#ifndef IswNscrollDCursor
#define IswNscrollDCursor ((String)&IswStrings[572])
#endif
#ifndef IswNscrollHCursor
#define IswNscrollHCursor ((String)&IswStrings[586])
#endif
#ifndef IswNscrollLCursor
#define IswNscrollLCursor ((String)&IswStrings[600])
#endif
#ifndef IswNscrollRCursor
#define IswNscrollRCursor ((String)&IswStrings[614])
#endif
#ifndef IswNscrollUCursor
#define IswNscrollUCursor ((String)&IswStrings[628])
#endif
#ifndef IswNscrollVCursor
#define IswNscrollVCursor ((String)&IswStrings[642])
#endif
#ifndef IswNselection
#define IswNselection ((String)&IswStrings[656])
#endif
#ifndef IswNselectionArray
#define IswNselectionArray ((String)&IswStrings[666])
#endif
#ifndef IswNsensitive
#define IswNsensitive ((String)&IswStrings[681])
#endif
#ifndef IswNshown
#define IswNshown ((String)&IswStrings[691])
#endif
#ifndef IswNspace
#define IswNspace ((String)&IswStrings[697])
#endif
#ifndef IswNstring
#define IswNstring ((String)&IswStrings[703])
#endif
#ifndef IswNtextOptions
#define IswNtextOptions ((String)&IswStrings[710])
#endif
#ifndef IswNtextSink
#define IswNtextSink ((String)&IswStrings[722])
#endif
#ifndef IswNtextSource
#define IswNtextSource ((String)&IswStrings[731])
#endif
#ifndef IswNthickness
#define IswNthickness ((String)&IswStrings[742])
#endif
#ifndef IswNthumbProc
#define IswNthumbProc ((String)&IswStrings[752])
#endif
#ifndef IswNtop
#define IswNtop ((String)&IswStrings[762])
#endif
#ifndef IswNtranslations
#define IswNtranslations ((String)&IswStrings[766])
#endif
#ifndef IswNunrealizeCallback
#define IswNunrealizeCallback ((String)&IswStrings[779])
#endif
#ifndef IswNupdate
#define IswNupdate ((String)&IswStrings[797])
#endif
#ifndef IswNuseBottom
#define IswNuseBottom ((String)&IswStrings[804])
#endif
#ifndef IswNuseRight
#define IswNuseRight ((String)&IswStrings[814])
#endif
#ifndef IswNvalue
#define IswNvalue ((String)&IswStrings[823])
#endif
#ifndef IswNvSpace
#define IswNvSpace ((String)&IswStrings[829])
#endif
#ifndef IswNwidth
#define IswNwidth ((String)&IswStrings[836])
#endif
#ifndef IswNwindow
#define IswNwindow ((String)&IswStrings[842])
#endif
#ifndef IswNx
#define IswNx ((String)&IswStrings[849])
#endif
#ifndef IswNy
#define IswNy ((String)&IswStrings[851])
#endif
#ifndef IswCAccelerators
#define IswCAccelerators ((String)&IswStrings[853])
#endif
#ifndef IswCBackground
#define IswCBackground ((String)&IswStrings[866])
#endif
#ifndef IswCBitmap
#define IswCBitmap ((String)&IswStrings[877])
#endif
#ifndef IswCBoolean
#define IswCBoolean ((String)&IswStrings[884])
#endif
#ifndef IswCBorderColor
#define IswCBorderColor ((String)&IswStrings[892])
#endif
#ifndef IswCBorderWidth
#define IswCBorderWidth ((String)&IswStrings[904])
#endif
#ifndef IswCCallback
#define IswCCallback ((String)&IswStrings[916])
#endif
#ifndef IswCColormap
#define IswCColormap ((String)&IswStrings[925])
#endif
#ifndef IswCColor
#define IswCColor ((String)&IswStrings[934])
#endif
#ifndef IswCCursor
#define IswCCursor ((String)&IswStrings[940])
#endif
#ifndef IswCDepth
#define IswCDepth ((String)&IswStrings[947])
#endif
#ifndef IswCEditType
#define IswCEditType ((String)&IswStrings[953])
#endif
#ifndef IswCEventBindings
#define IswCEventBindings ((String)&IswStrings[962])
#endif
#ifndef IswCFile
#define IswCFile ((String)&IswStrings[976])
#endif
#ifndef IswCFont
#define IswCFont ((String)&IswStrings[981])
#endif
#ifndef IswCForeground
#define IswCForeground ((String)&IswStrings[986])
#endif
#ifndef IswCFraction
#define IswCFraction ((String)&IswStrings[997])
#endif
#ifndef IswCFunction
#define IswCFunction ((String)&IswStrings[1006])
#endif
#ifndef IswCHeight
#define IswCHeight ((String)&IswStrings[1015])
#endif
#ifndef IswCHSpace
#define IswCHSpace ((String)&IswStrings[1022])
#endif
#ifndef IswCIndex
#define IswCIndex ((String)&IswStrings[1029])
#endif
#ifndef IswCInitialResourcesPersistent
#define IswCInitialResourcesPersistent ((String)&IswStrings[1035])
#endif
#ifndef IswCInsertPosition
#define IswCInsertPosition ((String)&IswStrings[1062])
#endif
#ifndef IswCInterval
#define IswCInterval ((String)&IswStrings[1077])
#endif
#ifndef IswCJustify
#define IswCJustify ((String)&IswStrings[1086])
#endif
#ifndef IswCKnobIndent
#define IswCKnobIndent ((String)&IswStrings[1094])
#endif
#ifndef IswCKnobPixel
#define IswCKnobPixel ((String)&IswStrings[1105])
#endif
#ifndef IswCLabel
#define IswCLabel ((String)&IswStrings[1115])
#endif
#ifndef IswCLength
#define IswCLength ((String)&IswStrings[1121])
#endif
#ifndef IswCMappedWhenManaged
#define IswCMappedWhenManaged ((String)&IswStrings[1128])
#endif
#ifndef IswCMargin
#define IswCMargin ((String)&IswStrings[1146])
#endif
#ifndef IswCMenuEntry
#define IswCMenuEntry ((String)&IswStrings[1153])
#endif
#ifndef IswCNotify
#define IswCNotify ((String)&IswStrings[1163])
#endif
#ifndef IswCOrientation
#define IswCOrientation ((String)&IswStrings[1170])
#endif
#ifndef IswCParameter
#define IswCParameter ((String)&IswStrings[1182])
#endif
#ifndef IswCPixmap
#define IswCPixmap ((String)&IswStrings[1192])
#endif
#ifndef IswCPosition
#define IswCPosition ((String)&IswStrings[1199])
#endif
#ifndef IswCReadOnly
#define IswCReadOnly ((String)&IswStrings[1208])
#endif
#ifndef IswCResize
#define IswCResize ((String)&IswStrings[1217])
#endif
#ifndef IswCReverseVideo
#define IswCReverseVideo ((String)&IswStrings[1224])
#endif
#ifndef IswCScreen
#define IswCScreen ((String)&IswStrings[1237])
#endif
#ifndef IswCScrollProc
#define IswCScrollProc ((String)&IswStrings[1244])
#endif
#ifndef IswCScrollDCursor
#define IswCScrollDCursor ((String)&IswStrings[1255])
#endif
#ifndef IswCScrollHCursor
#define IswCScrollHCursor ((String)&IswStrings[1269])
#endif
#ifndef IswCScrollLCursor
#define IswCScrollLCursor ((String)&IswStrings[1283])
#endif
#ifndef IswCScrollRCursor
#define IswCScrollRCursor ((String)&IswStrings[1297])
#endif
#ifndef IswCScrollUCursor
#define IswCScrollUCursor ((String)&IswStrings[1311])
#endif
#ifndef IswCScrollVCursor
#define IswCScrollVCursor ((String)&IswStrings[1325])
#endif
#ifndef IswCSelection
#define IswCSelection ((String)&IswStrings[1339])
#endif
#ifndef IswCSensitive
#define IswCSensitive ((String)&IswStrings[1349])
#endif
#ifndef IswCSelectionArray
#define IswCSelectionArray ((String)&IswStrings[1359])
#endif
#ifndef IswCSpace
#define IswCSpace ((String)&IswStrings[1374])
#endif
#ifndef IswCString
#define IswCString ((String)&IswStrings[1380])
#endif
#ifndef IswCTextOptions
#define IswCTextOptions ((String)&IswStrings[1387])
#endif
#ifndef IswCTextPosition
#define IswCTextPosition ((String)&IswStrings[1399])
#endif
#ifndef IswCTextSink
#define IswCTextSink ((String)&IswStrings[1412])
#endif
#ifndef IswCTextSource
#define IswCTextSource ((String)&IswStrings[1421])
#endif
#ifndef IswCThickness
#define IswCThickness ((String)&IswStrings[1432])
#endif
#ifndef IswCTranslations
#define IswCTranslations ((String)&IswStrings[1442])
#endif
#ifndef IswCValue
#define IswCValue ((String)&IswStrings[1455])
#endif
#ifndef IswCVSpace
#define IswCVSpace ((String)&IswStrings[1461])
#endif
#ifndef IswCWidth
#define IswCWidth ((String)&IswStrings[1468])
#endif
#ifndef IswCWindow
#define IswCWindow ((String)&IswStrings[1474])
#endif
#ifndef IswCX
#define IswCX ((String)&IswStrings[1481])
#endif
#ifndef IswCY
#define IswCY ((String)&IswStrings[1483])
#endif
#ifndef IswRAcceleratorTable
#define IswRAcceleratorTable ((String)&IswStrings[1485])
#endif
#ifndef IswRAtom
#define IswRAtom ((String)&IswStrings[1502])
#endif
#ifndef IswRBitmap
#define IswRBitmap ((String)&IswStrings[1507])
#endif
#ifndef IswRBool
#define IswRBool ((String)&IswStrings[1514])
#endif
#ifndef IswRBoolean
#define IswRBoolean ((String)&IswStrings[1519])
#endif
#ifndef IswRCallback
#define IswRCallback ((String)&IswStrings[1527])
#endif
#ifndef IswRCallProc
#define IswRCallProc ((String)&IswStrings[1536])
#endif
#ifndef IswRCardinal
#define IswRCardinal ((String)&IswStrings[1545])
#endif
#ifndef IswRColor
#define IswRColor ((String)&IswStrings[1554])
#endif
#ifndef IswRColormap
#define IswRColormap ((String)&IswStrings[1560])
#endif
#ifndef IswRCursor
#define IswRCursor ((String)&IswStrings[1569])
#endif
#ifndef IswRDimension
#define IswRDimension ((String)&IswStrings[1576])
#endif
#ifndef IswRDisplay
#define IswRDisplay ((String)&IswStrings[1586])
#endif
#ifndef IswREditMode
#define IswREditMode ((String)&IswStrings[1594])
#endif
#ifndef IswREnum
#define IswREnum ((String)&IswStrings[1603])
#endif
#ifndef IswRFile
#define IswRFile ((String)&IswStrings[1608])
#endif
#ifndef IswRFloat
#define IswRFloat ((String)&IswStrings[1613])
#endif
#ifndef IswRFont
#define IswRFont ((String)&IswStrings[1619])
#endif
#ifndef IswRFontStruct
#define IswRFontStruct ((String)&IswStrings[1624])
#endif
#ifndef IswRFunction
#define IswRFunction ((String)&IswStrings[1635])
#endif
#ifndef IswRGeometry
#define IswRGeometry ((String)&IswStrings[1644])
#endif
#ifndef IswRImmediate
#define IswRImmediate ((String)&IswStrings[1653])
#endif
#ifndef IswRInitialState
#define IswRInitialState ((String)&IswStrings[1663])
#endif
#ifndef IswRInt
#define IswRInt ((String)&IswStrings[1676])
#endif
#ifndef IswRJustify
#define IswRJustify ((String)&IswStrings[1680])
#endif
#ifndef IswRLongBoolean
#define IswRLongBoolean ((String)&IswStrings[1688])
#endif
#ifndef IswRObject
#define IswRObject ((String)&IswStrings[1693])
#endif
#ifndef IswROrientation
#define IswROrientation ((String)&IswStrings[1700])
#endif
#ifndef IswRPixel
#define IswRPixel ((String)&IswStrings[1712])
#endif
#ifndef IswRPixmap
#define IswRPixmap ((String)&IswStrings[1718])
#endif
#ifndef IswRPointer
#define IswRPointer ((String)&IswStrings[1725])
#endif
#ifndef IswRPosition
#define IswRPosition ((String)&IswStrings[1733])
#endif
#ifndef IswRScreen
#define IswRScreen ((String)&IswStrings[1742])
#endif
#ifndef IswRShort
#define IswRShort ((String)&IswStrings[1749])
#endif
#ifndef IswRString
#define IswRString ((String)&IswStrings[1755])
#endif
#ifndef IswRStringArray
#define IswRStringArray ((String)&IswStrings[1762])
#endif
#ifndef IswRStringTable
#define IswRStringTable ((String)&IswStrings[1774])
#endif
#ifndef IswRUnsignedChar
#define IswRUnsignedChar ((String)&IswStrings[1786])
#endif
#ifndef IswRTranslationTable
#define IswRTranslationTable ((String)&IswStrings[1799])
#endif
#ifndef IswRVisual
#define IswRVisual ((String)&IswStrings[1816])
#endif
#ifndef IswRWidget
#define IswRWidget ((String)&IswStrings[1823])
#endif
#ifndef IswRWidgetClass
#define IswRWidgetClass ((String)&IswStrings[1830])
#endif
#ifndef IswRWidgetList
#define IswRWidgetList ((String)&IswStrings[1842])
#endif
#ifndef IswRWindow
#define IswRWindow ((String)&IswStrings[1853])
#endif
#ifndef IswEoff
#define IswEoff ((String)&IswStrings[1860])
#endif
#ifndef IswEfalse
#define IswEfalse ((String)&IswStrings[1864])
#endif
#ifndef IswEno
#define IswEno ((String)&IswStrings[1870])
#endif
#ifndef IswEon
#define IswEon ((String)&IswStrings[1873])
#endif
#ifndef IswEtrue
#define IswEtrue ((String)&IswStrings[1876])
#endif
#ifndef IswEyes
#define IswEyes ((String)&IswStrings[1881])
#endif
#ifndef IswEvertical
#define IswEvertical ((String)&IswStrings[1885])
#endif
#ifndef IswEhorizontal
#define IswEhorizontal ((String)&IswStrings[1894])
#endif
#ifndef IswEtextRead
#define IswEtextRead ((String)&IswStrings[1905])
#endif
#ifndef IswEtextAppend
#define IswEtextAppend ((String)&IswStrings[1910])
#endif
#ifndef IswEtextEdit
#define IswEtextEdit ((String)&IswStrings[1917])
#endif
#ifndef IswExtdefaultbackground
#define IswExtdefaultbackground ((String)&IswStrings[1922])
#endif
#ifndef IswExtdefaultforeground
#define IswExtdefaultforeground ((String)&IswStrings[1942])
#endif
#ifndef IswExtdefaultfont
#define IswExtdefaultfont ((String)&IswStrings[1962])
#endif
#ifndef IswNfontSet
#define IswNfontSet ((String)&IswStrings[1976])
#endif
#ifndef IswRFontSet
#define IswRFontSet ((String)&IswStrings[1984])
#endif
#ifndef IswCFontSet
#define IswCFontSet ((String)&IswStrings[1992])
#endif
#ifndef IswRGravity
#define IswRGravity ((String)&IswStrings[2000])
#endif
#ifndef IswNcreateHook
#define IswNcreateHook ((String)&IswStrings[2008])
#endif
#ifndef IswNchangeHook
#define IswNchangeHook ((String)&IswStrings[2019])
#endif
#ifndef IswNconfigureHook
#define IswNconfigureHook ((String)&IswStrings[2030])
#endif
#ifndef IswNgeometryHook
#define IswNgeometryHook ((String)&IswStrings[2044])
#endif
#ifndef IswNdestroyHook
#define IswNdestroyHook ((String)&IswStrings[2057])
#endif
#ifndef IswNshells
#define IswNshells ((String)&IswStrings[2069])
#endif
#ifndef IswNnumShells
#define IswNnumShells ((String)&IswStrings[2076])
#endif
#ifndef IswHcreate
#define IswHcreate ((String)&IswStrings[2086])
#endif
#ifndef IswHsetValues
#define IswHsetValues ((String)&IswStrings[2096])
#endif
#ifndef IswHmanageChildren
#define IswHmanageChildren ((String)&IswStrings[2109])
#endif
#ifndef IswHunmanageChildren
#define IswHunmanageChildren ((String)&IswStrings[2127])
#endif
#ifndef IswHmanageSet
#define IswHmanageSet ((String)&IswStrings[2147])
#endif
#ifndef IswHunmanageSet
#define IswHunmanageSet ((String)&IswStrings[2160])
#endif
#ifndef IswHrealizeWidget
#define IswHrealizeWidget ((String)&IswStrings[2175])
#endif
#ifndef IswHunrealizeWidget
#define IswHunrealizeWidget ((String)&IswStrings[2192])
#endif
#ifndef IswHaddCallback
#define IswHaddCallback ((String)&IswStrings[2211])
#endif
#ifndef IswHaddCallbacks
#define IswHaddCallbacks ((String)&IswStrings[2226])
#endif
#ifndef IswHremoveCallback
#define IswHremoveCallback ((String)&IswStrings[2242])
#endif
#ifndef IswHremoveCallbacks
#define IswHremoveCallbacks ((String)&IswStrings[2260])
#endif
#ifndef IswHremoveAllCallbacks
#define IswHremoveAllCallbacks ((String)&IswStrings[2279])
#endif
#ifndef IswHaugmentTranslations
#define IswHaugmentTranslations ((String)&IswStrings[2301])
#endif
#ifndef IswHoverrideTranslations
#define IswHoverrideTranslations ((String)&IswStrings[2324])
#endif
#ifndef IswHuninstallTranslations
#define IswHuninstallTranslations ((String)&IswStrings[2348])
#endif
#ifndef IswHsetKeyboardFocus
#define IswHsetKeyboardFocus ((String)&IswStrings[2373])
#endif
#ifndef IswHsetWMColormapWindows
#define IswHsetWMColormapWindows ((String)&IswStrings[2393])
#endif
#ifndef IswHsetMappedWhenManaged
#define IswHsetMappedWhenManaged ((String)&IswStrings[2417])
#endif
#ifndef IswHmapWidget
#define IswHmapWidget ((String)&IswStrings[2441])
#endif
#ifndef IswHunmapWidget
#define IswHunmapWidget ((String)&IswStrings[2454])
#endif
#ifndef IswHpopup
#define IswHpopup ((String)&IswStrings[2469])
#endif
#ifndef IswHpopdown
#define IswHpopdown ((String)&IswStrings[2478])
#endif
#ifndef IswHconfigure
#define IswHconfigure ((String)&IswStrings[2489])
#endif
#ifndef IswHpreGeometry
#define IswHpreGeometry ((String)&IswStrings[2502])
#endif
#ifndef IswHpostGeometry
#define IswHpostGeometry ((String)&IswStrings[2517])
#endif
#ifndef IswHdestroy
#define IswHdestroy ((String)&IswStrings[2533])
#endif
#ifndef IswNtraversalOn
#define IswNtraversalOn ((String)&IswStrings[2544])
#endif
#ifndef IswCTraversalOn
#define IswCTraversalOn ((String)&IswStrings[2556])
#endif
#ifndef IswNtabIndex
#define IswNtabIndex ((String)&IswStrings[2568])
#endif
#ifndef IswCTabIndex
#define IswCTabIndex ((String)&IswStrings[2577])
#endif
#ifndef IswNconsumeTab
#define IswNconsumeTab ((String)&IswStrings[2586])
#endif
#ifndef IswCConsumeTab
#define IswCConsumeTab ((String)&IswStrings[2597])
#endif
#ifndef IswNmnemonicKey
#define IswNmnemonicKey ((String)&IswStrings[2608])
#endif
#ifndef IswCMnemonicKey
#define IswCMnemonicKey ((String)&IswStrings[2620])
#endif
#ifndef IswRWindowType
#define IswRWindowType ((String)&IswStrings[2632])
#endif
#ifndef IswNborderTop
#define IswNborderTop "borderTop"
#endif
#ifndef IswNborderRight
#define IswNborderRight "borderRight"
#endif
#ifndef IswNborderBottom
#define IswNborderBottom "borderBottom"
#endif
#ifndef IswNborderLeft
#define IswNborderLeft "borderLeft"
#endif
#endif /* ISWSTRINGDEFINES */

#ifndef ISWSTRINGDEFINES
#undef _IswStringDefs_h_Const
#endif

#endif /* _IswStringDefs_h_ */
