// Code generated by genargs from IswArgMacros.h; DO NOT EDIT.
// Generated: 2026-07-02T13:48:35Z

package isw

// --- ColorPicker ---

func (al *ArgList) ColorRed(v uintptr) *ArgList {
	return al.Add("colorRed", v)
}

func (al *ArgList) ColorGreen(v uintptr) *ArgList {
	return al.Add("colorGreen", v)
}

func (al *ArgList) ColorBlue(v uintptr) *ArgList {
	return al.Add("colorBlue", v)
}

func (al *ArgList) ColorChanged(fn CallbackFunc) *ArgList {
	return al.AddCallback("colorChanged", fn)
}

// --- Command ---

func (al *ArgList) CornerRadius(v uintptr) *ArgList {
	return al.Add("cornerRadius", v)
}

// --- Core (StringDefs.h) ---

func (al *ArgList) Accelerators(v string) *ArgList {
	return al.AddString("accelerators", v)
}

func (al *ArgList) AllowHoriz(v uintptr) *ArgList {
	return al.Add("allowHoriz", v)
}

func (al *ArgList) AllowVert(v uintptr) *ArgList {
	return al.Add("allowVert", v)
}

func (al *ArgList) AncestorSensitive(v uintptr) *ArgList {
	return al.Add("ancestorSensitive", v)
}

func (al *ArgList) Background(v uintptr) *ArgList {
	return al.Add("background", v)
}

func (al *ArgList) BackgroundImage(v uintptr) *ArgList {
	return al.Add("backgroundImage", v)
}

func (al *ArgList) Bitmap(v uintptr) *ArgList {
	return al.Add("bitmap", v)
}

func (al *ArgList) Border(v uintptr) *ArgList {
	return al.Add("border", v)
}

func (al *ArgList) BorderColor(v uintptr) *ArgList {
	return al.Add("borderColor", v)
}

func (al *ArgList) BorderWidth(v uintptr) *ArgList {
	return al.Add("borderWidth", v)
}

func (al *ArgList) BorderTop(v uintptr) *ArgList {
	return al.Add("borderTop", v)
}

func (al *ArgList) BorderRight(v uintptr) *ArgList {
	return al.Add("borderRight", v)
}

func (al *ArgList) BorderBottom(v uintptr) *ArgList {
	return al.Add("borderBottom", v)
}

func (al *ArgList) BorderLeft(v uintptr) *ArgList {
	return al.Add("borderLeft", v)
}

func (al *ArgList) Callback(fn CallbackFunc) *ArgList {
	return al.AddCallback("callback", fn)
}

func (al *ArgList) Colormap(v uintptr) *ArgList {
	return al.Add("colormap", v)
}

func (al *ArgList) Depth(v uintptr) *ArgList {
	return al.Add("depth", v)
}

func (al *ArgList) DestroyCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("destroyCallback", fn)
}

func (al *ArgList) EditType(v uintptr) *ArgList {
	return al.Add("editType", v)
}

func (al *ArgList) File(v string) *ArgList {
	return al.AddString("file", v)
}

func (al *ArgList) Font(v uintptr) *ArgList {
	return al.Add("font", v)
}

func (al *ArgList) FontSet(v uintptr) *ArgList {
	return al.Add("fontSet", v)
}

func (al *ArgList) ForceBars(v uintptr) *ArgList {
	return al.Add("forceBars", v)
}

func (al *ArgList) Foreground(v uintptr) *ArgList {
	return al.Add("foreground", v)
}

func (al *ArgList) Function(v uintptr) *ArgList {
	return al.Add("function", v)
}

func (al *ArgList) Height(v uintptr) *ArgList {
	return al.Add("height", v)
}

func (al *ArgList) Highlight(v uintptr) *ArgList {
	return al.Add("highlight", v)
}

func (al *ArgList) HSpace(v uintptr) *ArgList {
	return al.Add("hSpace", v)
}

func (al *ArgList) Index(v uintptr) *ArgList {
	return al.Add("index", v)
}

func (al *ArgList) InitialResourcesPersistent(v uintptr) *ArgList {
	return al.Add("initialResourcesPersistent", v)
}

func (al *ArgList) InnerHeight(v uintptr) *ArgList {
	return al.Add("innerHeight", v)
}

func (al *ArgList) InnerWidth(v uintptr) *ArgList {
	return al.Add("innerWidth", v)
}

func (al *ArgList) InnerWindow(v uintptr) *ArgList {
	return al.Add("innerWindow", v)
}

func (al *ArgList) InsertPosition(v uintptr) *ArgList {
	return al.Add("insertPosition", v)
}

func (al *ArgList) InternalHeight(v uintptr) *ArgList {
	return al.Add("internalHeight", v)
}

func (al *ArgList) InternalWidth(v uintptr) *ArgList {
	return al.Add("internalWidth", v)
}

func (al *ArgList) JumpProc(fn CallbackFunc) *ArgList {
	return al.AddCallback("jumpProc", fn)
}

func (al *ArgList) Justify(v uintptr) *ArgList {
	return al.Add("justify", v)
}

func (al *ArgList) KnobHeight(v uintptr) *ArgList {
	return al.Add("knobHeight", v)
}

func (al *ArgList) KnobIndent(v uintptr) *ArgList {
	return al.Add("knobIndent", v)
}

func (al *ArgList) KnobPixel(v uintptr) *ArgList {
	return al.Add("knobPixel", v)
}

func (al *ArgList) KnobWidth(v uintptr) *ArgList {
	return al.Add("knobWidth", v)
}

func (al *ArgList) Label(v string) *ArgList {
	return al.AddString("label", v)
}

func (al *ArgList) Length(v uintptr) *ArgList {
	return al.Add("length", v)
}

func (al *ArgList) LowerRight(v uintptr) *ArgList {
	return al.Add("lowerRight", v)
}

func (al *ArgList) MappedWhenManaged(v uintptr) *ArgList {
	return al.Add("mappedWhenManaged", v)
}

func (al *ArgList) MenuEntry(v uintptr) *ArgList {
	return al.Add("menuEntry", v)
}

func (al *ArgList) Name(v string) *ArgList {
	return al.AddString("name", v)
}

func (al *ArgList) Notify(fn CallbackFunc) *ArgList {
	return al.AddCallback("notify", fn)
}

func (al *ArgList) Orientation(v uintptr) *ArgList {
	return al.Add("orientation", v)
}

func (al *ArgList) Parameter(v uintptr) *ArgList {
	return al.Add("parameter", v)
}

func (al *ArgList) Pixmap(v uintptr) *ArgList {
	return al.Add("pixmap", v)
}

func (al *ArgList) PopdownCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("popdownCallback", fn)
}

func (al *ArgList) PopupCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("popupCallback", fn)
}

func (al *ArgList) Resize(v uintptr) *ArgList {
	return al.Add("resize", v)
}

func (al *ArgList) ReverseVideo(v uintptr) *ArgList {
	return al.Add("reverseVideo", v)
}

func (al *ArgList) Screen(v uintptr) *ArgList {
	return al.Add("screen", v)
}

func (al *ArgList) ScrollDCursor(v uintptr) *ArgList {
	return al.Add("scrollDCursor", v)
}

func (al *ArgList) ScrollHCursor(v uintptr) *ArgList {
	return al.Add("scrollHCursor", v)
}

func (al *ArgList) ScrollLCursor(v uintptr) *ArgList {
	return al.Add("scrollLCursor", v)
}

func (al *ArgList) ScrollProc(fn CallbackFunc) *ArgList {
	return al.AddCallback("scrollProc", fn)
}

func (al *ArgList) ScrollRCursor(v uintptr) *ArgList {
	return al.Add("scrollRCursor", v)
}

func (al *ArgList) ScrollUCursor(v uintptr) *ArgList {
	return al.Add("scrollUCursor", v)
}

func (al *ArgList) ScrollVCursor(v uintptr) *ArgList {
	return al.Add("scrollVCursor", v)
}

func (al *ArgList) Selection(v uintptr) *ArgList {
	return al.Add("selection", v)
}

func (al *ArgList) SelectionArray(v uintptr) *ArgList {
	return al.Add("selectionArray", v)
}

func (al *ArgList) Sensitive(v uintptr) *ArgList {
	return al.Add("sensitive", v)
}

func (al *ArgList) Shown(v uintptr) *ArgList {
	return al.Add("shown", v)
}

func (al *ArgList) Space(v uintptr) *ArgList {
	return al.Add("space", v)
}

func (al *ArgList) String(v string) *ArgList {
	return al.AddString("string", v)
}

func (al *ArgList) TextOptions(v uintptr) *ArgList {
	return al.Add("textOptions", v)
}

func (al *ArgList) TextSink(v uintptr) *ArgList {
	return al.Add("textSink", v)
}

func (al *ArgList) TextSource(v uintptr) *ArgList {
	return al.Add("textSource", v)
}

func (al *ArgList) Thickness(v uintptr) *ArgList {
	return al.Add("thickness", v)
}

func (al *ArgList) ThumbProc(fn CallbackFunc) *ArgList {
	return al.AddCallback("thumbProc", fn)
}

func (al *ArgList) Top(v uintptr) *ArgList {
	return al.Add("top", v)
}

func (al *ArgList) Translations(v uintptr) *ArgList {
	return al.Add("translations", v)
}

func (al *ArgList) UnrealizeCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("unrealizeCallback", fn)
}

func (al *ArgList) Update(v uintptr) *ArgList {
	return al.Add("update", v)
}

func (al *ArgList) UseBottom(v uintptr) *ArgList {
	return al.Add("useBottom", v)
}

func (al *ArgList) UseRight(v uintptr) *ArgList {
	return al.Add("useRight", v)
}

func (al *ArgList) Value(v uintptr) *ArgList {
	return al.Add("value", v)
}

func (al *ArgList) VSpace(v uintptr) *ArgList {
	return al.Add("vSpace", v)
}

func (al *ArgList) Width(v uintptr) *ArgList {
	return al.Add("width", v)
}

func (al *ArgList) Window(v uintptr) *ArgList {
	return al.Add("window", v)
}

func (al *ArgList) X(v uintptr) *ArgList {
	return al.Add("x", v)
}

func (al *ArgList) Y(v uintptr) *ArgList {
	return al.Add("y", v)
}

// --- Dialog / Layout / Template / Reports / ProgressBar / Grip ---

func (al *ArgList) Layout(v uintptr) *ArgList {
	return al.Add("layout", v)
}

func (al *ArgList) Debug(v uintptr) *ArgList {
	return al.Add("debug", v)
}

func (al *ArgList) TemplateResource(v string) *ArgList {
	return al.AddString("templateResource", v)
}

func (al *ArgList) ReportCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("reportCallback", fn)
}

func (al *ArgList) GripTranslations(v uintptr) *ArgList {
	return al.Add("gripTranslations", v)
}

// --- DrawingArea ---

func (al *ArgList) ExposeCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("exposeCallback", fn)
}

func (al *ArgList) ResizeCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("resizeCallback", fn)
}

func (al *ArgList) InputCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("inputCallback", fn)
}

// --- FileChooser ---

func (al *ArgList) FileMode(v uintptr) *ArgList {
	return al.Add("fileMode", v)
}

func (al *ArgList) InitialDirectory(v string) *ArgList {
	return al.AddString("initialDirectory", v)
}

func (al *ArgList) FileFilters(v []string) *ArgList {
	return al.AddStringList("fileFilters", v)
}

func (al *ArgList) NumFileFilters(v uintptr) *ArgList {
	return al.Add("numFileFilters", v)
}

func (al *ArgList) FileSelected(fn CallbackFunc) *ArgList {
	return al.AddCallback("fileSelected", fn)
}

func (al *ArgList) FileCancelled(fn CallbackFunc) *ArgList {
	return al.AddCallback("fileCancelled", fn)
}

// --- FlexBox ---

func (al *ArgList) Spacing(v uintptr) *ArgList {
	return al.Add("spacing", v)
}

func (al *ArgList) FillWeight(v uintptr) *ArgList {
	return al.Add("fillWeight", v)
}

func (al *ArgList) FixedSize(v uintptr) *ArgList {
	return al.Add("fixedSize", v)
}

func (al *ArgList) Align(v uintptr) *ArgList {
	return al.Add("align", v)
}

// Compatibility delegates
func (al *ArgList) FlexGrow(v uintptr) *ArgList  { return al.FillWeight(v) }
func (al *ArgList) FlexBasis(v uintptr) *ArgList  { return al.FixedSize(v) }
func (al *ArgList) FlexAlign(v uintptr) *ArgList  { return al.Align(v) }

// --- FontChooser ---

func (al *ArgList) FontFamily(v string) *ArgList {
	return al.AddString("fontFamily", v)
}

func (al *ArgList) FontSize(v uintptr) *ArgList {
	return al.Add("fontSize", v)
}

func (al *ArgList) FontWeight(v uintptr) *ArgList {
	return al.Add("fontWeight", v)
}

func (al *ArgList) FontSlant(v uintptr) *ArgList {
	return al.Add("fontSlant", v)
}

func (al *ArgList) PreviewText(v string) *ArgList {
	return al.AddString("previewText", v)
}

func (al *ArgList) FontChanged(fn CallbackFunc) *ArgList {
	return al.AddCallback("fontChanged", fn)
}

// --- Form — edge chain constraints take IswEdgeType (IswChainTop/Bottom/Left/Right/IswRubber) ---

func (al *ArgList) DefaultDistance(v uintptr) *ArgList {
	return al.Add("defaultDistance", v)
}

func (al *ArgList) Bottom(v uintptr) *ArgList {
	return al.Add("bottom", v)
}

func (al *ArgList) Left(v uintptr) *ArgList {
	return al.Add("left", v)
}

func (al *ArgList) Right(v uintptr) *ArgList {
	return al.Add("right", v)
}

func (al *ArgList) FromHoriz(v Widget) *ArgList {
	return al.AddWidget("fromHoriz", v)
}

func (al *ArgList) FromVert(v Widget) *ArgList {
	return al.AddWidget("fromVert", v)
}

func (al *ArgList) HorizDistance(v uintptr) *ArgList {
	return al.Add("horizDistance", v)
}

func (al *ArgList) VertDistance(v uintptr) *ArgList {
	return al.Add("vertDistance", v)
}

func (al *ArgList) Resizable(v uintptr) *ArgList {
	return al.Add("resizable", v)
}

// --- ISWImP ---

func (al *ArgList) InputMethod(v string) *ArgList {
	return al.AddString("inputMethod", v)
}

func (al *ArgList) PreeditType(v string) *ArgList {
	return al.AddString("preeditType", v)
}

func (al *ArgList) OpenIm(v uintptr) *ArgList {
	return al.Add("openIm", v)
}

func (al *ArgList) SharedIc(v uintptr) *ArgList {
	return al.Add("sharedIc", v)
}

// --- IconView ---

func (al *ArgList) IconLabels(v []string) *ArgList {
	return al.AddStringList("iconLabels", v)
}

func (al *ArgList) IconData(v uintptr) *ArgList {
	return al.Add("iconData", v)
}

func (al *ArgList) NumIcons(v uintptr) *ArgList {
	return al.Add("numIcons", v)
}

func (al *ArgList) IconSize(v uintptr) *ArgList {
	return al.Add("iconSize", v)
}

func (al *ArgList) ItemSpacing(v uintptr) *ArgList {
	return al.Add("itemSpacing", v)
}

func (al *ArgList) LabelLines(v uintptr) *ArgList {
	return al.Add("labelLines", v)
}

func (al *ArgList) SelectCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("selectCallback", fn)
}

func (al *ArgList) MultiSelect(v uintptr) *ArgList {
	return al.Add("multiSelect", v)
}

func (al *ArgList) CursorItem(v uintptr) *ArgList {
	return al.Add("cursorItem", v)
}

// --- IswDragDrop ---

func (al *ArgList) DropCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("dropCallback", fn)
}

func (al *ArgList) DragEnterCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("dragEnterCallback", fn)
}

func (al *ArgList) DragMotionCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("dragMotionCallback", fn)
}

func (al *ArgList) DragLeaveCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("dragLeaveCallback", fn)
}

// --- Label ---

func (al *ArgList) Ellipsize(v uintptr) *ArgList {
	return al.Add("ellipsize", v)
}

func (al *ArgList) Image(v uintptr) *ArgList {
	return al.Add("image", v)
}

func (al *ArgList) LeftImage(v uintptr) *ArgList {
	return al.Add("leftImage", v)
}

func (al *ArgList) Encoding(v string) *ArgList {
	return al.AddString("encoding", v)
}

// --- List ---

func (al *ArgList) Cursor(v uintptr) *ArgList {
	return al.Add("cursor", v)
}

func (al *ArgList) ColumnSpacing(v uintptr) *ArgList {
	return al.Add("columnSpacing", v)
}

func (al *ArgList) DefaultColumns(v uintptr) *ArgList {
	return al.Add("defaultColumns", v)
}

func (al *ArgList) ForceColumns(v uintptr) *ArgList {
	return al.Add("forceColumns", v)
}

func (al *ArgList) List(v []string) *ArgList {
	return al.AddStringList("list", v)
}

func (al *ArgList) Longest(v uintptr) *ArgList {
	return al.Add("longest", v)
}

func (al *ArgList) NumberStrings(v uintptr) *ArgList {
	return al.Add("numberStrings", v)
}

func (al *ArgList) PasteBuffer(v uintptr) *ArgList {
	return al.Add("pasteBuffer", v)
}

func (al *ArgList) RowSpacing(v uintptr) *ArgList {
	return al.Add("rowSpacing", v)
}

func (al *ArgList) VerticalList(v uintptr) *ArgList {
	return al.Add("verticalList", v)
}

func (al *ArgList) DropdownMode(v uintptr) *ArgList {
	return al.Add("dropdownMode", v)
}

// --- ListBox ---

func (al *ArgList) SelectionMode(v uintptr) *ArgList {
	return al.Add("selectionMode", v)
}

func (al *ArgList) ShowSeparators(v uintptr) *ArgList {
	return al.Add("showSeparators", v)
}

func (al *ArgList) ActivateCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("activateCallback", fn)
}

// --- ListBox constraint ---

func (al *ArgList) Selectable(v uintptr) *ArgList {
	return al.Add("selectable", v)
}

func (al *ArgList) ListBoxRowHeight(v uintptr) *ArgList {
	return al.Add("listBoxRowHeight", v)
}

func (al *ArgList) Separator(v uintptr) *ArgList {
	return al.Add("separator", v)
}

// --- ListBox groups (constraint resources on nested-ListBox children) ---

func (al *ArgList) PivotLabel(v string) *ArgList {
	return al.AddString("pivotLabel", v)
}

func (al *ArgList) PivotOpen(v uintptr) *ArgList {
	return al.Add("pivotOpen", v)
}

func (al *ArgList) PivotImage(v string) *ArgList {
	return al.AddString("pivotImage", v)
}

func (al *ArgList) PivotImageOpen(v string) *ArgList {
	return al.AddString("pivotImageOpen", v)
}

func (al *ArgList) PivotCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("pivotCallback", fn)
}

// --- ListBoxRow ---

func (al *ArgList) RowPadding(v uintptr) *ArgList {
	return al.Add("rowPadding", v)
}

// --- ListView ---

func (al *ArgList) ListViewColumns(v uintptr) *ArgList {
	return al.Add("listViewColumns", v)
}

func (al *ArgList) NumColumns(v uintptr) *ArgList {
	return al.Add("numColumns", v)
}

func (al *ArgList) NumRows(v uintptr) *ArgList {
	return al.Add("numRows", v)
}

func (al *ArgList) ListViewData(v uintptr) *ArgList {
	return al.Add("listViewData", v)
}

func (al *ArgList) RowHeight(v uintptr) *ArgList {
	return al.Add("rowHeight", v)
}

func (al *ArgList) HeaderHeight(v uintptr) *ArgList {
	return al.Add("headerHeight", v)
}

func (al *ArgList) CursorRow(v uintptr) *ArgList {
	return al.Add("cursorRow", v)
}

func (al *ArgList) ShowHeader(v uintptr) *ArgList {
	return al.Add("showHeader", v)
}

func (al *ArgList) ReorderCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("reorderCallback", fn)
}

// --- Menu mnemonics and accelerators (SmeBSB, MenuButton) ---

func (al *ArgList) MnemonicKey(v uintptr) *ArgList {
	return al.Add("mnemonicKey", v)
}

func (al *ArgList) Accelerator(v string) *ArgList {
	return al.AddString("accelerator", v)
}

func (al *ArgList) AcceleratorText(v string) *ArgList {
	return al.AddString("acceleratorText", v)
}

// --- Paned ---

func (al *ArgList) AllowResize(v uintptr) *ArgList {
	return al.Add("allowResize", v)
}

func (al *ArgList) BetweenCursor(v uintptr) *ArgList {
	return al.Add("betweenCursor", v)
}

func (al *ArgList) VerticalBetweenCursor(v uintptr) *ArgList {
	return al.Add("verticalBetweenCursor", v)
}

func (al *ArgList) HorizontalBetweenCursor(v uintptr) *ArgList {
	return al.Add("horizontalBetweenCursor", v)
}

func (al *ArgList) GripCursor(v uintptr) *ArgList {
	return al.Add("gripCursor", v)
}

func (al *ArgList) GripIndent(v uintptr) *ArgList {
	return al.Add("gripIndent", v)
}

func (al *ArgList) HorizontalGripCursor(v uintptr) *ArgList {
	return al.Add("horizontalGripCursor", v)
}

func (al *ArgList) InternalBorderColor(v uintptr) *ArgList {
	return al.Add("internalBorderColor", v)
}

func (al *ArgList) InternalBorderWidth(v uintptr) *ArgList {
	return al.Add("internalBorderWidth", v)
}

func (al *ArgList) RefigureMode(v uintptr) *ArgList {
	return al.Add("refigureMode", v)
}

func (al *ArgList) Position(v uintptr) *ArgList {
	return al.Add("position", v)
}

func (al *ArgList) Min(v uintptr) *ArgList {
	return al.Add("min", v)
}

func (al *ArgList) Max(v uintptr) *ArgList {
	return al.Add("max", v)
}

func (al *ArgList) PreferredPaneSize(v uintptr) *ArgList {
	return al.Add("preferredPaneSize", v)
}

func (al *ArgList) ResizeToPreferred(v uintptr) *ArgList {
	return al.Add("resizeToPreferred", v)
}

func (al *ArgList) ShowGrip(v uintptr) *ArgList {
	return al.Add("showGrip", v)
}

func (al *ArgList) SkipAdjust(v uintptr) *ArgList {
	return al.Add("skipAdjust", v)
}

func (al *ArgList) VerticalGripCursor(v uintptr) *ArgList {
	return al.Add("verticalGripCursor", v)
}

// --- Panner ---

func (al *ArgList) AllowOff(v uintptr) *ArgList {
	return al.Add("allowOff", v)
}

func (al *ArgList) DefaultScale(v uintptr) *ArgList {
	return al.Add("defaultScale", v)
}

func (al *ArgList) CanvasWidth(v uintptr) *ArgList {
	return al.Add("canvasWidth", v)
}

func (al *ArgList) CanvasHeight(v uintptr) *ArgList {
	return al.Add("canvasHeight", v)
}

func (al *ArgList) InternalSpace(v uintptr) *ArgList {
	return al.Add("internalSpace", v)
}

func (al *ArgList) LineWidth(v uintptr) *ArgList {
	return al.Add("lineWidth", v)
}

func (al *ArgList) RubberBand(v uintptr) *ArgList {
	return al.Add("rubberBand", v)
}

func (al *ArgList) SliderX(v uintptr) *ArgList {
	return al.Add("sliderX", v)
}

func (al *ArgList) SliderY(v uintptr) *ArgList {
	return al.Add("sliderY", v)
}

func (al *ArgList) SliderWidth(v uintptr) *ArgList {
	return al.Add("sliderWidth", v)
}

func (al *ArgList) SliderHeight(v uintptr) *ArgList {
	return al.Add("sliderHeight", v)
}

// --- Repeater ---

func (al *ArgList) Decay(v uintptr) *ArgList {
	return al.Add("decay", v)
}

func (al *ArgList) InitialDelay(v uintptr) *ArgList {
	return al.Add("initialDelay", v)
}

func (al *ArgList) MinimumDelay(v uintptr) *ArgList {
	return al.Add("minimumDelay", v)
}

func (al *ArgList) RepeatDelay(v uintptr) *ArgList {
	return al.Add("repeatDelay", v)
}

func (al *ArgList) Flash(v uintptr) *ArgList {
	return al.Add("flash", v)
}

func (al *ArgList) StartCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("startCallback", fn)
}

func (al *ArgList) StopCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("stopCallback", fn)
}

// --- Scrollbar ---

func (al *ArgList) MinimumThumb(v uintptr) *ArgList {
	return al.Add("minimumThumb", v)
}

func (al *ArgList) TopOfThumb(v uintptr) *ArgList {
	return al.Add("topOfThumb", v)
}

func (al *ArgList) PickTop(v uintptr) *ArgList {
	return al.Add("pickTop", v)
}

func (al *ArgList) ScrollWheelIncrement(v uintptr) *ArgList {
	return al.Add("scrollWheelIncrement", v)
}

// --- Shell ---

func (al *ArgList) IconName(v string) *ArgList {
	return al.AddString("iconName", v)
}

func (al *ArgList) IconPixmap(v uintptr) *ArgList {
	return al.Add("iconPixmap", v)
}

func (al *ArgList) IconWindow(v uintptr) *ArgList {
	return al.Add("iconWindow", v)
}

func (al *ArgList) IconMask(v uintptr) *ArgList {
	return al.Add("iconMask", v)
}

func (al *ArgList) WindowGroup(v uintptr) *ArgList {
	return al.Add("windowGroup", v)
}

func (al *ArgList) Visual(v uintptr) *ArgList {
	return al.Add("visual", v)
}

func (al *ArgList) TitleEncoding(v uintptr) *ArgList {
	return al.Add("titleEncoding", v)
}

func (al *ArgList) SaveUnder(v uintptr) *ArgList {
	return al.Add("saveUnder", v)
}

func (al *ArgList) Transient(v uintptr) *ArgList {
	return al.Add("transient", v)
}

func (al *ArgList) OverrideRedirect(v uintptr) *ArgList {
	return al.Add("overrideRedirect", v)
}

func (al *ArgList) TransientFor(v Widget) *ArgList {
	return al.AddWidget("transientFor", v)
}

func (al *ArgList) IconNameEncoding(v uintptr) *ArgList {
	return al.Add("iconNameEncoding", v)
}

func (al *ArgList) AllowShellResize(v uintptr) *ArgList {
	return al.Add("allowShellResize", v)
}

func (al *ArgList) CreatePopupChildProc(v uintptr) *ArgList {
	return al.Add("createPopupChildProc", v)
}

func (al *ArgList) Title(v string) *ArgList {
	return al.AddString("title", v)
}

func (al *ArgList) Argc(v uintptr) *ArgList {
	return al.Add("argc", v)
}

func (al *ArgList) Argv(v uintptr) *ArgList {
	return al.Add("argv", v)
}

func (al *ArgList) IconX(v uintptr) *ArgList {
	return al.Add("iconX", v)
}

func (al *ArgList) IconY(v uintptr) *ArgList {
	return al.Add("iconY", v)
}

func (al *ArgList) Input(v uintptr) *ArgList {
	return al.Add("input", v)
}

func (al *ArgList) Iconic(v uintptr) *ArgList {
	return al.Add("iconic", v)
}

func (al *ArgList) InitialState(v uintptr) *ArgList {
	return al.Add("initialState", v)
}

func (al *ArgList) Geometry(v string) *ArgList {
	return al.AddString("geometry", v)
}

func (al *ArgList) BaseWidth(v uintptr) *ArgList {
	return al.Add("baseWidth", v)
}

func (al *ArgList) BaseHeight(v uintptr) *ArgList {
	return al.Add("baseHeight", v)
}

func (al *ArgList) WinGravity(v uintptr) *ArgList {
	return al.Add("winGravity", v)
}

func (al *ArgList) MinWidth(v uintptr) *ArgList {
	return al.Add("minWidth", v)
}

func (al *ArgList) MinHeight(v uintptr) *ArgList {
	return al.Add("minHeight", v)
}

func (al *ArgList) MaxWidth(v uintptr) *ArgList {
	return al.Add("maxWidth", v)
}

func (al *ArgList) MaxHeight(v uintptr) *ArgList {
	return al.Add("maxHeight", v)
}

func (al *ArgList) WidthInc(v uintptr) *ArgList {
	return al.Add("widthInc", v)
}

func (al *ArgList) HeightInc(v uintptr) *ArgList {
	return al.Add("heightInc", v)
}

func (al *ArgList) MinAspectY(v uintptr) *ArgList {
	return al.Add("minAspectY", v)
}

func (al *ArgList) MaxAspectY(v uintptr) *ArgList {
	return al.Add("maxAspectY", v)
}

func (al *ArgList) MinAspectX(v uintptr) *ArgList {
	return al.Add("minAspectX", v)
}

func (al *ArgList) MaxAspectX(v uintptr) *ArgList {
	return al.Add("maxAspectX", v)
}

func (al *ArgList) WmTimeout(v uintptr) *ArgList {
	return al.Add("wmTimeout", v)
}

func (al *ArgList) WaitForWm(v uintptr) *ArgList {
	return al.Add("waitForWm", v)
}

func (al *ArgList) ClientLeader(v Widget) *ArgList {
	return al.AddWidget("clientLeader", v)
}

func (al *ArgList) WindowRole(v string) *ArgList {
	return al.AddString("windowRole", v)
}

func (al *ArgList) Urgency(v uintptr) *ArgList {
	return al.Add("urgency", v)
}

// --- Shell — window type and struts ---

func (al *ArgList) WindowType(v uintptr) *ArgList {
	return al.Add("windowType", v)
}

func (al *ArgList) StrutLeft(v uintptr) *ArgList {
	return al.Add("strutLeft", v)
}

func (al *ArgList) StrutRight(v uintptr) *ArgList {
	return al.Add("strutRight", v)
}

func (al *ArgList) StrutTop(v uintptr) *ArgList {
	return al.Add("strutTop", v)
}

func (al *ArgList) StrutBottom(v uintptr) *ArgList {
	return al.Add("strutBottom", v)
}

// --- Simple ---

func (al *ArgList) ActiveColor(v uintptr) *ArgList {
	return al.Add("activeColor", v)
}

func (al *ArgList) CursorName(v string) *ArgList {
	return al.AddString("cursorName", v)
}

func (al *ArgList) International(v uintptr) *ArgList {
	return al.Add("international", v)
}

func (al *ArgList) TraversalOn(v uintptr) *ArgList {
	return al.Add("traversalOn", v)
}

func (al *ArgList) TabIndex(v uintptr) *ArgList {
	return al.Add("tabIndex", v)
}

// --- SimpleMenu ---

func (al *ArgList) ColumnWidth(v uintptr) *ArgList {
	return al.Add("columnWidth", v)
}

func (al *ArgList) JumpScroll(v uintptr) *ArgList {
	return al.Add("jumpScroll", v)
}

func (al *ArgList) LabelClass(v uintptr) *ArgList {
	return al.Add("labelClass", v)
}

func (al *ArgList) LeftWhitespace(v uintptr) *ArgList {
	return al.Add("leftWhitespace", v)
}

func (al *ArgList) MenuOnScreen(v uintptr) *ArgList {
	return al.Add("menuOnScreen", v)
}

func (al *ArgList) PopupOnEntry(v uintptr) *ArgList {
	return al.Add("popupOnEntry", v)
}

func (al *ArgList) RightWhitespace(v uintptr) *ArgList {
	return al.Add("rightWhitespace", v)
}

// --- Slider ---

func (al *ArgList) MinimumValue(v uintptr) *ArgList {
	return al.Add("minimumValue", v)
}

func (al *ArgList) MaximumValue(v uintptr) *ArgList {
	return al.Add("maximumValue", v)
}

func (al *ArgList) SliderValue(v uintptr) *ArgList {
	return al.Add("sliderValue", v)
}

func (al *ArgList) ShowValue(v uintptr) *ArgList {
	return al.Add("showValue", v)
}

func (al *ArgList) ValueChanged(fn CallbackFunc) *ArgList {
	return al.AddCallback("valueChanged", fn)
}

func (al *ArgList) ValuePosition(v uintptr) *ArgList {
	return al.Add("valuePosition", v)
}

func (al *ArgList) TickInterval(v uintptr) *ArgList {
	return al.Add("tickInterval", v)
}

// --- SmeBSB ---

func (al *ArgList) RightImage(v uintptr) *ArgList {
	return al.Add("rightImage", v)
}

func (al *ArgList) Underline(v uintptr) *ArgList {
	return al.Add("underline", v)
}

func (al *ArgList) VertSpace(v uintptr) *ArgList {
	return al.Add("vertSpace", v)
}

// --- SpinBox ---

func (al *ArgList) SpinMinimum(v uintptr) *ArgList {
	return al.Add("spinMinimum", v)
}

func (al *ArgList) SpinMaximum(v uintptr) *ArgList {
	return al.Add("spinMaximum", v)
}

func (al *ArgList) SpinValue(v uintptr) *ArgList {
	return al.Add("spinValue", v)
}

func (al *ArgList) SpinIncrement(v uintptr) *ArgList {
	return al.Add("spinIncrement", v)
}

func (al *ArgList) SpinWrap(v uintptr) *ArgList {
	return al.Add("spinWrap", v)
}

// --- StatusBar / Toolbar / MenuButton ---

func (al *ArgList) StatusStretch(v uintptr) *ArgList {
	return al.Add("statusStretch", v)
}

func (al *ArgList) ToolbarAlignment(v uintptr) *ArgList {
	return al.Add("toolbarAlignment", v)
}

func (al *ArgList) MenuName(v string) *ArgList {
	return al.AddString("menuName", v)
}

// --- Tabs ---

func (al *ArgList) TabCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("tabCallback", fn)
}

func (al *ArgList) TopWidget(v Widget) *ArgList {
	return al.AddWidget("topWidget", v)
}

func (al *ArgList) TabLabel(v string) *ArgList {
	return al.AddString("tabLabel", v)
}

func (al *ArgList) TabHeight(v uintptr) *ArgList {
	return al.Add("tabHeight", v)
}

func (al *ArgList) TabSizing(v uintptr) *ArgList {
	return al.Add("tabSizing", v)
}

func (al *ArgList) TabBackground(v uintptr) *ArgList {
	return al.Add("tabBackground", v)
}

func (al *ArgList) ActiveTabColor(v uintptr) *ArgList {
	return al.Add("activeTabColor", v)
}

func (al *ArgList) TabBorderColor(v uintptr) *ArgList {
	return al.Add("tabBorderColor", v)
}

// --- Text ---

func (al *ArgList) AutoFill(v uintptr) *ArgList {
	return al.Add("autoFill", v)
}

func (al *ArgList) BottomMargin(v uintptr) *ArgList {
	return al.Add("bottomMargin", v)
}

func (al *ArgList) DialogHOffset(v uintptr) *ArgList {
	return al.Add("dialogHOffset", v)
}

func (al *ArgList) DialogVOffset(v uintptr) *ArgList {
	return al.Add("dialogVOffset", v)
}

func (al *ArgList) DisplayCaret(v uintptr) *ArgList {
	return al.Add("displayCaret", v)
}

func (al *ArgList) DisplayPosition(v uintptr) *ArgList {
	return al.Add("displayPosition", v)
}

func (al *ArgList) LeftMargin(v uintptr) *ArgList {
	return al.Add("leftMargin", v)
}

func (al *ArgList) RightMargin(v uintptr) *ArgList {
	return al.Add("rightMargin", v)
}

func (al *ArgList) ScrollVertical(v uintptr) *ArgList {
	return al.Add("scrollVertical", v)
}

func (al *ArgList) ScrollHorizontal(v uintptr) *ArgList {
	return al.Add("scrollHorizontal", v)
}

func (al *ArgList) SelectTypes(v uintptr) *ArgList {
	return al.Add("selectTypes", v)
}

func (al *ArgList) TopMargin(v uintptr) *ArgList {
	return al.Add("topMargin", v)
}

func (al *ArgList) Wrap(v uintptr) *ArgList {
	return al.Add("wrap", v)
}

func (al *ArgList) ConsumeTab(v uintptr) *ArgList {
	return al.Add("consumeTab", v)
}

// --- TextSink ---

func (al *ArgList) DisplayNonprinting(v uintptr) *ArgList {
	return al.Add("displayNonprinting", v)
}

func (al *ArgList) Echo(v uintptr) *ArgList {
	return al.Add("echo", v)
}

// --- TextSrc ---

func (al *ArgList) DataCompression(v uintptr) *ArgList {
	return al.Add("dataCompression", v)
}

func (al *ArgList) PieceSize(v uintptr) *ArgList {
	return al.Add("pieceSize", v)
}

func (al *ArgList) Type(v uintptr) *ArgList {
	return al.Add("type", v)
}

func (al *ArgList) UseStringInPlace(v uintptr) *ArgList {
	return al.Add("useStringInPlace", v)
}

// --- Tip ---

func (al *ArgList) Timeout(v uintptr) *ArgList {
	return al.Add("timeout", v)
}

func (al *ArgList) Tip(v string) *ArgList {
	return al.AddString("tip", v)
}

// --- Toggle ---

func (al *ArgList) State(v uintptr) *ArgList {
	return al.Add("state", v)
}

func (al *ArgList) RadioGroup(v Widget) *ArgList {
	return al.AddWidget("radioGroup", v)
}

func (al *ArgList) RadioData(v uintptr) *ArgList {
	return al.Add("radioData", v)
}

func (al *ArgList) ToggleShape(v uintptr) *ArgList {
	return al.Add("toggleShape", v)
}

// --- Tree ---

func (al *ArgList) AutoReconfigure(v uintptr) *ArgList {
	return al.Add("autoReconfigure", v)
}

func (al *ArgList) TreeForeground(v uintptr) *ArgList {
	return al.Add("treeForeground", v)
}

func (al *ArgList) TreeParent(v Widget) *ArgList {
	return al.AddWidget("treeParent", v)
}

func (al *ArgList) Gravity(v uintptr) *ArgList {
	return al.Add("gravity", v)
}

