// Code generated by genargs from IswArgMacros.h; DO NOT EDIT.
// Generated: 2026-07-06T05:46:16Z

package isw

// --- ColorPicker ---

func (al *ArgList) ColorRed(v int) *ArgList {
	return al.Add("colorRed", v)
}

func (al *ArgList) ColorGreen(v int) *ArgList {
	return al.Add("colorGreen", v)
}

func (al *ArgList) ColorBlue(v int) *ArgList {
	return al.Add("colorBlue", v)
}

func (al *ArgList) ColorChanged(fn CallbackFunc) *ArgList {
	return al.AddCallback("colorChanged", fn)
}

// --- Command ---

func (al *ArgList) CornerRadius(v int) *ArgList {
	return al.Add("cornerRadius", v)
}

// --- Compatibility aliases ---

func (al *ArgList) FlexGrow(v int) *ArgList {
	return al.Add("fillWeight", v)
}

func (al *ArgList) FlexBasis(v int) *ArgList {
	return al.Add("fixedSize", v)
}

func (al *ArgList) FlexAlign(v int) *ArgList {
	return al.Add("align", v)
}

// --- Core (StringDefs.h) ---

func (al *ArgList) Accelerators(v string) *ArgList {
	return al.AddString("accelerators", v)
}

func (al *ArgList) AllowHoriz(v bool) *ArgList {
	return al.AddBool("allowHoriz", v)
}

func (al *ArgList) AllowVert(v bool) *ArgList {
	return al.AddBool("allowVert", v)
}

func (al *ArgList) AncestorSensitive(v int) *ArgList {
	return al.Add("ancestorSensitive", v)
}

func (al *ArgList) Background(v Pixel) *ArgList {
	return al.Add("background", int(v))
}

func (al *ArgList) BackgroundImage(v int) *ArgList {
	return al.Add("backgroundImage", v)
}

func (al *ArgList) Bitmap(v int) *ArgList {
	return al.Add("bitmap", v)
}

func (al *ArgList) Border(v int) *ArgList {
	return al.Add("border", v)
}

func (al *ArgList) BorderColor(v Pixel) *ArgList {
	return al.Add("borderColor", int(v))
}

func (al *ArgList) BorderWidth(v int) *ArgList {
	return al.Add("borderWidth", v)
}

func (al *ArgList) BorderTop(v int) *ArgList {
	return al.Add("borderTop", v)
}

func (al *ArgList) BorderRight(v int) *ArgList {
	return al.Add("borderRight", v)
}

func (al *ArgList) BorderBottom(v int) *ArgList {
	return al.Add("borderBottom", v)
}

func (al *ArgList) BorderLeft(v int) *ArgList {
	return al.Add("borderLeft", v)
}

func (al *ArgList) Callback(fn CallbackFunc) *ArgList {
	return al.AddCallback("callback", fn)
}

func (al *ArgList) Colormap(v int) *ArgList {
	return al.Add("colormap", v)
}

func (al *ArgList) Depth(v int) *ArgList {
	return al.Add("depth", v)
}

func (al *ArgList) DestroyCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("destroyCallback", fn)
}

func (al *ArgList) EditType(v TextEditType) *ArgList {
	return al.Add("editType", int(v))
}

func (al *ArgList) File(v string) *ArgList {
	return al.AddString("file", v)
}

func (al *ArgList) Font(v int) *ArgList {
	return al.Add("font", v)
}

func (al *ArgList) FontSet(v int) *ArgList {
	return al.Add("fontSet", v)
}

func (al *ArgList) ForceBars(v int) *ArgList {
	return al.Add("forceBars", v)
}

func (al *ArgList) Foreground(v Pixel) *ArgList {
	return al.Add("foreground", int(v))
}

func (al *ArgList) Function(v int) *ArgList {
	return al.Add("function", v)
}

func (al *ArgList) Height(v int) *ArgList {
	return al.Add("height", v)
}

func (al *ArgList) Highlight(v int) *ArgList {
	return al.Add("highlight", v)
}

func (al *ArgList) HSpace(v int) *ArgList {
	return al.Add("hSpace", v)
}

func (al *ArgList) Index(v int) *ArgList {
	return al.Add("index", v)
}

func (al *ArgList) InitialResourcesPersistent(v int) *ArgList {
	return al.Add("initialResourcesPersistent", v)
}

func (al *ArgList) InnerHeight(v int) *ArgList {
	return al.Add("innerHeight", v)
}

func (al *ArgList) InnerWidth(v int) *ArgList {
	return al.Add("innerWidth", v)
}

func (al *ArgList) InnerWindow(v int) *ArgList {
	return al.Add("innerWindow", v)
}

func (al *ArgList) InsertPosition(v int) *ArgList {
	return al.Add("insertPosition", v)
}

func (al *ArgList) InternalHeight(v int) *ArgList {
	return al.Add("internalHeight", v)
}

func (al *ArgList) InternalWidth(v int) *ArgList {
	return al.Add("internalWidth", v)
}

func (al *ArgList) JumpProc(fn CallbackFunc) *ArgList {
	return al.AddCallback("jumpProc", fn)
}

func (al *ArgList) Justify(v Justify) *ArgList {
	return al.Add("justify", int(v))
}

func (al *ArgList) KnobHeight(v int) *ArgList {
	return al.Add("knobHeight", v)
}

func (al *ArgList) KnobIndent(v int) *ArgList {
	return al.Add("knobIndent", v)
}

func (al *ArgList) KnobPixel(v int) *ArgList {
	return al.Add("knobPixel", v)
}

func (al *ArgList) KnobWidth(v int) *ArgList {
	return al.Add("knobWidth", v)
}

func (al *ArgList) Label(v string) *ArgList {
	return al.AddString("label", v)
}

func (al *ArgList) Length(v int) *ArgList {
	return al.Add("length", v)
}

func (al *ArgList) LowerRight(v int) *ArgList {
	return al.Add("lowerRight", v)
}

func (al *ArgList) MappedWhenManaged(v bool) *ArgList {
	return al.AddBool("mappedWhenManaged", v)
}

func (al *ArgList) MenuEntry(v int) *ArgList {
	return al.Add("menuEntry", v)
}

func (al *ArgList) Name(v string) *ArgList {
	return al.AddString("name", v)
}

func (al *ArgList) Notify(fn CallbackFunc) *ArgList {
	return al.AddCallback("notify", fn)
}

func (al *ArgList) Orientation(v Orientation) *ArgList {
	return al.Add("orientation", int(v))
}

func (al *ArgList) Parameter(v int) *ArgList {
	return al.Add("parameter", v)
}

func (al *ArgList) Pixmap(v int) *ArgList {
	return al.Add("pixmap", v)
}

func (al *ArgList) PopdownCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("popdownCallback", fn)
}

func (al *ArgList) PopupCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("popupCallback", fn)
}

func (al *ArgList) Resize(v bool) *ArgList {
	return al.AddBool("resize", v)
}

func (al *ArgList) ReverseVideo(v int) *ArgList {
	return al.Add("reverseVideo", v)
}

func (al *ArgList) Screen(v int) *ArgList {
	return al.Add("screen", v)
}

func (al *ArgList) ScrollDCursor(v int) *ArgList {
	return al.Add("scrollDCursor", v)
}

func (al *ArgList) ScrollHCursor(v int) *ArgList {
	return al.Add("scrollHCursor", v)
}

func (al *ArgList) ScrollLCursor(v int) *ArgList {
	return al.Add("scrollLCursor", v)
}

func (al *ArgList) ScrollProc(fn CallbackFunc) *ArgList {
	return al.AddCallback("scrollProc", fn)
}

func (al *ArgList) ScrollRCursor(v int) *ArgList {
	return al.Add("scrollRCursor", v)
}

func (al *ArgList) ScrollUCursor(v int) *ArgList {
	return al.Add("scrollUCursor", v)
}

func (al *ArgList) ScrollVCursor(v int) *ArgList {
	return al.Add("scrollVCursor", v)
}

func (al *ArgList) Selection(v int) *ArgList {
	return al.Add("selection", v)
}

func (al *ArgList) SelectionArray(v int) *ArgList {
	return al.Add("selectionArray", v)
}

func (al *ArgList) Sensitive(v bool) *ArgList {
	return al.AddBool("sensitive", v)
}

func (al *ArgList) Shown(v int) *ArgList {
	return al.Add("shown", v)
}

func (al *ArgList) Space(v int) *ArgList {
	return al.Add("space", v)
}

func (al *ArgList) String(v string) *ArgList {
	return al.AddString("string", v)
}

func (al *ArgList) TextOptions(v int) *ArgList {
	return al.Add("textOptions", v)
}

func (al *ArgList) TextSink(v int) *ArgList {
	return al.Add("textSink", v)
}

func (al *ArgList) TextSource(v int) *ArgList {
	return al.Add("textSource", v)
}

func (al *ArgList) Thickness(v int) *ArgList {
	return al.Add("thickness", v)
}

func (al *ArgList) ThumbProc(fn CallbackFunc) *ArgList {
	return al.AddCallback("thumbProc", fn)
}

func (al *ArgList) Top(v EdgeType) *ArgList {
	return al.Add("top", int(v))
}

func (al *ArgList) Translations(v int) *ArgList {
	return al.Add("translations", v)
}

func (al *ArgList) UnrealizeCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("unrealizeCallback", fn)
}

func (al *ArgList) Update(v int) *ArgList {
	return al.Add("update", v)
}

func (al *ArgList) UseBottom(v int) *ArgList {
	return al.Add("useBottom", v)
}

func (al *ArgList) UseRight(v int) *ArgList {
	return al.Add("useRight", v)
}

func (al *ArgList) Value(v int) *ArgList {
	return al.Add("value", v)
}

func (al *ArgList) VSpace(v int) *ArgList {
	return al.Add("vSpace", v)
}

func (al *ArgList) Width(v int) *ArgList {
	return al.Add("width", v)
}

func (al *ArgList) Window(v int) *ArgList {
	return al.Add("window", v)
}

func (al *ArgList) X(v int) *ArgList {
	return al.Add("x", v)
}

func (al *ArgList) Y(v int) *ArgList {
	return al.Add("y", v)
}

// --- Dialog / Layout / Template / Reports / ProgressBar / Grip ---

func (al *ArgList) Layout(v int) *ArgList {
	return al.Add("layout", v)
}

func (al *ArgList) Debug(v int) *ArgList {
	return al.Add("debug", v)
}

func (al *ArgList) TemplateResource(v string) *ArgList {
	return al.AddString("templateResource", v)
}

func (al *ArgList) ReportCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("reportCallback", fn)
}

func (al *ArgList) GripTranslations(v int) *ArgList {
	return al.Add("gripTranslations", v)
}

// --- DrawingArea ---

func (al *ArgList) ExposeCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("exposeCallback", fn)
}

func (al *ArgList) ResizeCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("resizeCallback", fn)
}

func (al *ArgList) InputCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("inputCallback", fn)
}

// --- FileChooser ---

func (al *ArgList) FileMode(v FileChooserMode) *ArgList {
	return al.Add("fileMode", int(v))
}

func (al *ArgList) InitialDirectory(v string) *ArgList {
	return al.AddString("initialDirectory", v)
}

func (al *ArgList) FileFilters(v []FileChooserFilter) *ArgList {
	return al.addFileFilters(v)
}

func (al *ArgList) NumFileFilters(v int) *ArgList {
	return al.Add("numFileFilters", v)
}

func (al *ArgList) FileSelected(fn CallbackFunc) *ArgList {
	return al.AddCallback("fileSelected", fn)
}

func (al *ArgList) FileCancelled(fn CallbackFunc) *ArgList {
	return al.AddCallback("fileCancelled", fn)
}

// --- FlexBox ---

func (al *ArgList) Spacing(v int) *ArgList {
	return al.Add("spacing", v)
}

func (al *ArgList) FillWeight(v int) *ArgList {
	return al.Add("fillWeight", v)
}

func (al *ArgList) FixedSize(v int) *ArgList {
	return al.Add("fixedSize", v)
}

func (al *ArgList) Align(v int) *ArgList {
	return al.Add("align", v)
}

// --- FontChooser ---

func (al *ArgList) FontFamily(v string) *ArgList {
	return al.AddString("fontFamily", v)
}

func (al *ArgList) FontSize(v int) *ArgList {
	return al.Add("fontSize", v)
}

func (al *ArgList) FontWeight(v int) *ArgList {
	return al.Add("fontWeight", v)
}

func (al *ArgList) FontSlant(v int) *ArgList {
	return al.Add("fontSlant", v)
}

func (al *ArgList) PreviewText(v string) *ArgList {
	return al.AddString("previewText", v)
}

func (al *ArgList) FontChanged(fn CallbackFunc) *ArgList {
	return al.AddCallback("fontChanged", fn)
}

// --- Form — edge chain constraints take IswEdgeType (IswChainTop/Bottom/Left/Right/IswRubber) ---

func (al *ArgList) DefaultDistance(v int) *ArgList {
	return al.Add("defaultDistance", v)
}

func (al *ArgList) Bottom(v EdgeType) *ArgList {
	return al.Add("bottom", int(v))
}

func (al *ArgList) Left(v EdgeType) *ArgList {
	return al.Add("left", int(v))
}

func (al *ArgList) Right(v EdgeType) *ArgList {
	return al.Add("right", int(v))
}

func (al *ArgList) FromHoriz(v Widget) *ArgList {
	return al.AddWidget("fromHoriz", v)
}

func (al *ArgList) FromVert(v Widget) *ArgList {
	return al.AddWidget("fromVert", v)
}

func (al *ArgList) HorizDistance(v int) *ArgList {
	return al.Add("horizDistance", v)
}

func (al *ArgList) VertDistance(v int) *ArgList {
	return al.Add("vertDistance", v)
}

func (al *ArgList) Resizable(v int) *ArgList {
	return al.Add("resizable", v)
}

// --- ISWImP ---

func (al *ArgList) InputMethod(v string) *ArgList {
	return al.AddString("inputMethod", v)
}

func (al *ArgList) PreeditType(v string) *ArgList {
	return al.AddString("preeditType", v)
}

func (al *ArgList) OpenIm(v int) *ArgList {
	return al.Add("openIm", v)
}

func (al *ArgList) SharedIc(v int) *ArgList {
	return al.Add("sharedIc", v)
}

// --- IconView ---

func (al *ArgList) IconLabels(v []string) *ArgList {
	return al.AddStringList("iconLabels", v)
}

func (al *ArgList) IconData(v int) *ArgList {
	return al.Add("iconData", v)
}

func (al *ArgList) NumIcons(v int) *ArgList {
	return al.Add("numIcons", v)
}

func (al *ArgList) IconSize(v int) *ArgList {
	return al.Add("iconSize", v)
}

func (al *ArgList) ItemSpacing(v int) *ArgList {
	return al.Add("itemSpacing", v)
}

func (al *ArgList) LabelLines(v int) *ArgList {
	return al.Add("labelLines", v)
}

func (al *ArgList) SelectCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("selectCallback", fn)
}

func (al *ArgList) MultiSelect(v bool) *ArgList {
	return al.AddBool("multiSelect", v)
}

func (al *ArgList) CursorItem(v int) *ArgList {
	return al.Add("cursorItem", v)
}

// --- IswDragDrop ---

func (al *ArgList) DropCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("dropCallback", fn)
}

func (al *ArgList) DragEnterCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("dragEnterCallback", fn)
}

func (al *ArgList) DragMotionCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("dragMotionCallback", fn)
}

func (al *ArgList) DragLeaveCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("dragLeaveCallback", fn)
}

// --- Label ---

func (al *ArgList) Ellipsize(v Ellipsize) *ArgList {
	return al.Add("ellipsize", int(v))
}

func (al *ArgList) Image(v int) *ArgList {
	return al.Add("image", v)
}

func (al *ArgList) LeftImage(v int) *ArgList {
	return al.Add("leftImage", v)
}

func (al *ArgList) Encoding(v string) *ArgList {
	return al.AddString("encoding", v)
}

// --- List ---

func (al *ArgList) Cursor(v int) *ArgList {
	return al.Add("cursor", v)
}

func (al *ArgList) ColumnSpacing(v int) *ArgList {
	return al.Add("columnSpacing", v)
}

func (al *ArgList) DefaultColumns(v int) *ArgList {
	return al.Add("defaultColumns", v)
}

func (al *ArgList) ForceColumns(v bool) *ArgList {
	return al.AddBool("forceColumns", v)
}

func (al *ArgList) List(v []string) *ArgList {
	return al.AddStringList("list", v)
}

func (al *ArgList) Longest(v int) *ArgList {
	return al.Add("longest", v)
}

func (al *ArgList) NumberStrings(v int) *ArgList {
	return al.Add("numberStrings", v)
}

func (al *ArgList) PasteBuffer(v int) *ArgList {
	return al.Add("pasteBuffer", v)
}

func (al *ArgList) RowSpacing(v int) *ArgList {
	return al.Add("rowSpacing", v)
}

func (al *ArgList) VerticalList(v bool) *ArgList {
	return al.AddBool("verticalList", v)
}

func (al *ArgList) DropdownMode(v int) *ArgList {
	return al.Add("dropdownMode", v)
}

// --- ListBox ---

func (al *ArgList) SelectionMode(v int) *ArgList {
	return al.Add("selectionMode", v)
}

func (al *ArgList) ShowSeparators(v int) *ArgList {
	return al.Add("showSeparators", v)
}

func (al *ArgList) ActivateCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("activateCallback", fn)
}

// --- ListBox constraint ---

func (al *ArgList) Selectable(v int) *ArgList {
	return al.Add("selectable", v)
}

func (al *ArgList) ListBoxRowHeight(v int) *ArgList {
	return al.Add("listBoxRowHeight", v)
}

func (al *ArgList) Separator(v int) *ArgList {
	return al.Add("separator", v)
}

// --- ListBox groups (constraint resources on nested-ListBox children) ---

func (al *ArgList) PivotLabel(v string) *ArgList {
	return al.AddString("pivotLabel", v)
}

func (al *ArgList) PivotOpen(v int) *ArgList {
	return al.Add("pivotOpen", v)
}

func (al *ArgList) PivotImage(v string) *ArgList {
	return al.AddString("pivotImage", v)
}

func (al *ArgList) PivotImageOpen(v string) *ArgList {
	return al.AddString("pivotImageOpen", v)
}

func (al *ArgList) PivotCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("pivotCallback", fn)
}

// --- ListBoxRow ---

func (al *ArgList) RowPadding(v int) *ArgList {
	return al.Add("rowPadding", v)
}

// --- ListView ---

func (al *ArgList) ListViewColumns(v int) *ArgList {
	return al.Add("listViewColumns", v)
}

func (al *ArgList) NumColumns(v int) *ArgList {
	return al.Add("numColumns", v)
}

func (al *ArgList) NumRows(v int) *ArgList {
	return al.Add("numRows", v)
}

func (al *ArgList) ListViewData(v int) *ArgList {
	return al.Add("listViewData", v)
}

func (al *ArgList) RowHeight(v int) *ArgList {
	return al.Add("rowHeight", v)
}

func (al *ArgList) HeaderHeight(v int) *ArgList {
	return al.Add("headerHeight", v)
}

func (al *ArgList) CursorRow(v int) *ArgList {
	return al.Add("cursorRow", v)
}

func (al *ArgList) ShowHeader(v int) *ArgList {
	return al.Add("showHeader", v)
}

func (al *ArgList) ReorderCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("reorderCallback", fn)
}

// --- Menu mnemonics and accelerators (SmeBSB, MenuButton) ---

func (al *ArgList) MnemonicKey(v int) *ArgList {
	return al.Add("mnemonicKey", v)
}

func (al *ArgList) Accelerator(v string) *ArgList {
	return al.AddString("accelerator", v)
}

func (al *ArgList) AcceleratorText(v string) *ArgList {
	return al.AddString("acceleratorText", v)
}

// --- Paned ---

func (al *ArgList) AllowResize(v bool) *ArgList {
	return al.AddBool("allowResize", v)
}

func (al *ArgList) BetweenCursor(v int) *ArgList {
	return al.Add("betweenCursor", v)
}

func (al *ArgList) VerticalBetweenCursor(v int) *ArgList {
	return al.Add("verticalBetweenCursor", v)
}

func (al *ArgList) HorizontalBetweenCursor(v int) *ArgList {
	return al.Add("horizontalBetweenCursor", v)
}

func (al *ArgList) GripCursor(v int) *ArgList {
	return al.Add("gripCursor", v)
}

func (al *ArgList) GripIndent(v int) *ArgList {
	return al.Add("gripIndent", v)
}

func (al *ArgList) HorizontalGripCursor(v int) *ArgList {
	return al.Add("horizontalGripCursor", v)
}

func (al *ArgList) InternalBorderColor(v int) *ArgList {
	return al.Add("internalBorderColor", v)
}

func (al *ArgList) InternalBorderWidth(v int) *ArgList {
	return al.Add("internalBorderWidth", v)
}

func (al *ArgList) RefigureMode(v int) *ArgList {
	return al.Add("refigureMode", v)
}

func (al *ArgList) Position(v int) *ArgList {
	return al.Add("position", v)
}

func (al *ArgList) Min(v int) *ArgList {
	return al.Add("min", v)
}

func (al *ArgList) Max(v int) *ArgList {
	return al.Add("max", v)
}

func (al *ArgList) PreferredPaneSize(v int) *ArgList {
	return al.Add("preferredPaneSize", v)
}

func (al *ArgList) ResizeToPreferred(v int) *ArgList {
	return al.Add("resizeToPreferred", v)
}

func (al *ArgList) ShowGrip(v bool) *ArgList {
	return al.AddBool("showGrip", v)
}

func (al *ArgList) SkipAdjust(v int) *ArgList {
	return al.Add("skipAdjust", v)
}

func (al *ArgList) VerticalGripCursor(v int) *ArgList {
	return al.Add("verticalGripCursor", v)
}

// --- Panner ---

func (al *ArgList) AllowOff(v int) *ArgList {
	return al.Add("allowOff", v)
}

func (al *ArgList) DefaultScale(v int) *ArgList {
	return al.Add("defaultScale", v)
}

func (al *ArgList) CanvasWidth(v int) *ArgList {
	return al.Add("canvasWidth", v)
}

func (al *ArgList) CanvasHeight(v int) *ArgList {
	return al.Add("canvasHeight", v)
}

func (al *ArgList) InternalSpace(v int) *ArgList {
	return al.Add("internalSpace", v)
}

func (al *ArgList) LineWidth(v int) *ArgList {
	return al.Add("lineWidth", v)
}

func (al *ArgList) RubberBand(v int) *ArgList {
	return al.Add("rubberBand", v)
}

func (al *ArgList) SliderX(v int) *ArgList {
	return al.Add("sliderX", v)
}

func (al *ArgList) SliderY(v int) *ArgList {
	return al.Add("sliderY", v)
}

func (al *ArgList) SliderWidth(v int) *ArgList {
	return al.Add("sliderWidth", v)
}

func (al *ArgList) SliderHeight(v int) *ArgList {
	return al.Add("sliderHeight", v)
}

// --- Repeater ---

func (al *ArgList) Decay(v int) *ArgList {
	return al.Add("decay", v)
}

func (al *ArgList) InitialDelay(v int) *ArgList {
	return al.Add("initialDelay", v)
}

func (al *ArgList) MinimumDelay(v int) *ArgList {
	return al.Add("minimumDelay", v)
}

func (al *ArgList) RepeatDelay(v int) *ArgList {
	return al.Add("repeatDelay", v)
}

func (al *ArgList) Flash(v int) *ArgList {
	return al.Add("flash", v)
}

func (al *ArgList) StartCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("startCallback", fn)
}

func (al *ArgList) StopCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("stopCallback", fn)
}

// --- Scrollbar ---

func (al *ArgList) MinimumThumb(v int) *ArgList {
	return al.Add("minimumThumb", v)
}

func (al *ArgList) TopOfThumb(v int) *ArgList {
	return al.Add("topOfThumb", v)
}

func (al *ArgList) PickTop(v int) *ArgList {
	return al.Add("pickTop", v)
}

func (al *ArgList) ScrollWheelIncrement(v int) *ArgList {
	return al.Add("scrollWheelIncrement", v)
}

// --- Shell ---

func (al *ArgList) IconName(v string) *ArgList {
	return al.AddString("iconName", v)
}

func (al *ArgList) IconPixmap(v int) *ArgList {
	return al.Add("iconPixmap", v)
}

func (al *ArgList) IconWindow(v int) *ArgList {
	return al.Add("iconWindow", v)
}

func (al *ArgList) IconMask(v int) *ArgList {
	return al.Add("iconMask", v)
}

func (al *ArgList) WindowGroup(v int) *ArgList {
	return al.Add("windowGroup", v)
}

func (al *ArgList) Visual(v int) *ArgList {
	return al.Add("visual", v)
}

func (al *ArgList) TitleEncoding(v int) *ArgList {
	return al.Add("titleEncoding", v)
}

func (al *ArgList) SaveUnder(v int) *ArgList {
	return al.Add("saveUnder", v)
}

func (al *ArgList) Transient(v int) *ArgList {
	return al.Add("transient", v)
}

func (al *ArgList) OverrideRedirect(v int) *ArgList {
	return al.Add("overrideRedirect", v)
}

func (al *ArgList) TransientFor(v Widget) *ArgList {
	return al.AddWidget("transientFor", v)
}

func (al *ArgList) IconNameEncoding(v int) *ArgList {
	return al.Add("iconNameEncoding", v)
}

func (al *ArgList) AllowShellResize(v bool) *ArgList {
	return al.AddBool("allowShellResize", v)
}

func (al *ArgList) CreatePopupChildProc(v int) *ArgList {
	return al.Add("createPopupChildProc", v)
}

func (al *ArgList) Title(v string) *ArgList {
	return al.AddString("title", v)
}

func (al *ArgList) Argc(v int) *ArgList {
	return al.Add("argc", v)
}

func (al *ArgList) Argv(v int) *ArgList {
	return al.Add("argv", v)
}

func (al *ArgList) IconX(v int) *ArgList {
	return al.Add("iconX", v)
}

func (al *ArgList) IconY(v int) *ArgList {
	return al.Add("iconY", v)
}

func (al *ArgList) Input(v int) *ArgList {
	return al.Add("input", v)
}

func (al *ArgList) Iconic(v int) *ArgList {
	return al.Add("iconic", v)
}

func (al *ArgList) InitialState(v int) *ArgList {
	return al.Add("initialState", v)
}

func (al *ArgList) Geometry(v string) *ArgList {
	return al.AddString("geometry", v)
}

func (al *ArgList) BaseWidth(v int) *ArgList {
	return al.Add("baseWidth", v)
}

func (al *ArgList) BaseHeight(v int) *ArgList {
	return al.Add("baseHeight", v)
}

func (al *ArgList) WinGravity(v int) *ArgList {
	return al.Add("winGravity", v)
}

func (al *ArgList) MinWidth(v int) *ArgList {
	return al.Add("minWidth", v)
}

func (al *ArgList) MinHeight(v int) *ArgList {
	return al.Add("minHeight", v)
}

func (al *ArgList) MaxWidth(v int) *ArgList {
	return al.Add("maxWidth", v)
}

func (al *ArgList) MaxHeight(v int) *ArgList {
	return al.Add("maxHeight", v)
}

func (al *ArgList) WidthInc(v int) *ArgList {
	return al.Add("widthInc", v)
}

func (al *ArgList) HeightInc(v int) *ArgList {
	return al.Add("heightInc", v)
}

func (al *ArgList) MinAspectY(v int) *ArgList {
	return al.Add("minAspectY", v)
}

func (al *ArgList) MaxAspectY(v int) *ArgList {
	return al.Add("maxAspectY", v)
}

func (al *ArgList) MinAspectX(v int) *ArgList {
	return al.Add("minAspectX", v)
}

func (al *ArgList) MaxAspectX(v int) *ArgList {
	return al.Add("maxAspectX", v)
}

func (al *ArgList) WmTimeout(v int) *ArgList {
	return al.Add("wmTimeout", v)
}

func (al *ArgList) WaitForWm(v int) *ArgList {
	return al.Add("waitForWm", v)
}

func (al *ArgList) ClientLeader(v Widget) *ArgList {
	return al.AddWidget("clientLeader", v)
}

func (al *ArgList) WindowRole(v string) *ArgList {
	return al.AddString("windowRole", v)
}

func (al *ArgList) Urgency(v int) *ArgList {
	return al.Add("urgency", v)
}

// --- Shell — window type and struts ---

func (al *ArgList) WindowType(v int) *ArgList {
	return al.Add("windowType", v)
}

func (al *ArgList) StrutLeft(v int) *ArgList {
	return al.Add("strutLeft", v)
}

func (al *ArgList) StrutRight(v int) *ArgList {
	return al.Add("strutRight", v)
}

func (al *ArgList) StrutTop(v int) *ArgList {
	return al.Add("strutTop", v)
}

func (al *ArgList) StrutBottom(v int) *ArgList {
	return al.Add("strutBottom", v)
}

// --- Simple ---

func (al *ArgList) ActiveColor(v Pixel) *ArgList {
	return al.Add("activeColor", int(v))
}

func (al *ArgList) CursorName(v string) *ArgList {
	return al.AddString("cursorName", v)
}

func (al *ArgList) International(v int) *ArgList {
	return al.Add("international", v)
}

func (al *ArgList) TraversalOn(v bool) *ArgList {
	return al.AddBool("traversalOn", v)
}

func (al *ArgList) TabIndex(v int) *ArgList {
	return al.Add("tabIndex", v)
}

// --- SimpleMenu ---

func (al *ArgList) ColumnWidth(v int) *ArgList {
	return al.Add("columnWidth", v)
}

func (al *ArgList) JumpScroll(v int) *ArgList {
	return al.Add("jumpScroll", v)
}

func (al *ArgList) LabelClass(v int) *ArgList {
	return al.Add("labelClass", v)
}

func (al *ArgList) LeftWhitespace(v int) *ArgList {
	return al.Add("leftWhitespace", v)
}

func (al *ArgList) MenuOnScreen(v int) *ArgList {
	return al.Add("menuOnScreen", v)
}

func (al *ArgList) PopupOnEntry(v int) *ArgList {
	return al.Add("popupOnEntry", v)
}

func (al *ArgList) RightWhitespace(v int) *ArgList {
	return al.Add("rightWhitespace", v)
}

// --- Slider ---

func (al *ArgList) MinimumValue(v int) *ArgList {
	return al.Add("minimumValue", v)
}

func (al *ArgList) MaximumValue(v int) *ArgList {
	return al.Add("maximumValue", v)
}

func (al *ArgList) SliderValue(v int) *ArgList {
	return al.Add("sliderValue", v)
}

func (al *ArgList) ShowValue(v bool) *ArgList {
	return al.AddBool("showValue", v)
}

func (al *ArgList) ValueChanged(fn CallbackFunc) *ArgList {
	return al.AddCallback("valueChanged", fn)
}

func (al *ArgList) ValuePosition(v SliderValuePosition) *ArgList {
	return al.Add("valuePosition", int(v))
}

func (al *ArgList) TickInterval(v int) *ArgList {
	return al.Add("tickInterval", v)
}

// --- SmeBSB ---

func (al *ArgList) RightImage(v int) *ArgList {
	return al.Add("rightImage", v)
}

func (al *ArgList) Underline(v int) *ArgList {
	return al.Add("underline", v)
}

func (al *ArgList) VertSpace(v int) *ArgList {
	return al.Add("vertSpace", v)
}

// --- SpinBox ---

func (al *ArgList) SpinMinimum(v int) *ArgList {
	return al.Add("spinMinimum", v)
}

func (al *ArgList) SpinMaximum(v int) *ArgList {
	return al.Add("spinMaximum", v)
}

func (al *ArgList) SpinValue(v int) *ArgList {
	return al.Add("spinValue", v)
}

func (al *ArgList) SpinIncrement(v int) *ArgList {
	return al.Add("spinIncrement", v)
}

func (al *ArgList) SpinWrap(v int) *ArgList {
	return al.Add("spinWrap", v)
}

// --- StatusBar / Toolbar / MenuButton ---

func (al *ArgList) StatusStretch(v int) *ArgList {
	return al.Add("statusStretch", v)
}

func (al *ArgList) ToolbarAlignment(v int) *ArgList {
	return al.Add("toolbarAlignment", v)
}

func (al *ArgList) MenuName(v string) *ArgList {
	return al.AddString("menuName", v)
}

// --- Tabs ---

func (al *ArgList) TabCallback(fn CallbackFunc) *ArgList {
	return al.AddCallback("tabCallback", fn)
}

func (al *ArgList) TopWidget(v Widget) *ArgList {
	return al.AddWidget("topWidget", v)
}

func (al *ArgList) TabLabel(v string) *ArgList {
	return al.AddString("tabLabel", v)
}

func (al *ArgList) TabHeight(v int) *ArgList {
	return al.Add("tabHeight", v)
}

func (al *ArgList) TabSizing(v int) *ArgList {
	return al.Add("tabSizing", v)
}

func (al *ArgList) TabBackground(v int) *ArgList {
	return al.Add("tabBackground", v)
}

func (al *ArgList) ActiveTabColor(v int) *ArgList {
	return al.Add("activeTabColor", v)
}

func (al *ArgList) TabBorderColor(v int) *ArgList {
	return al.Add("tabBorderColor", v)
}

// --- Text ---

func (al *ArgList) AutoFill(v int) *ArgList {
	return al.Add("autoFill", v)
}

func (al *ArgList) BottomMargin(v int) *ArgList {
	return al.Add("bottomMargin", v)
}

func (al *ArgList) DialogHOffset(v int) *ArgList {
	return al.Add("dialogHOffset", v)
}

func (al *ArgList) DialogVOffset(v int) *ArgList {
	return al.Add("dialogVOffset", v)
}

func (al *ArgList) DisplayCaret(v int) *ArgList {
	return al.Add("displayCaret", v)
}

func (al *ArgList) DisplayPosition(v int) *ArgList {
	return al.Add("displayPosition", v)
}

func (al *ArgList) LeftMargin(v int) *ArgList {
	return al.Add("leftMargin", v)
}

func (al *ArgList) RightMargin(v int) *ArgList {
	return al.Add("rightMargin", v)
}

func (al *ArgList) ScrollVertical(v TextScrollMode) *ArgList {
	return al.Add("scrollVertical", int(v))
}

func (al *ArgList) ScrollHorizontal(v TextScrollMode) *ArgList {
	return al.Add("scrollHorizontal", int(v))
}

func (al *ArgList) SelectTypes(v int) *ArgList {
	return al.Add("selectTypes", v)
}

func (al *ArgList) TopMargin(v int) *ArgList {
	return al.Add("topMargin", v)
}

func (al *ArgList) Wrap(v TextWrapMode) *ArgList {
	return al.Add("wrap", int(v))
}

func (al *ArgList) ConsumeTab(v int) *ArgList {
	return al.Add("consumeTab", v)
}

// --- TextSink ---

func (al *ArgList) DisplayNonprinting(v int) *ArgList {
	return al.Add("displayNonprinting", v)
}

func (al *ArgList) Echo(v int) *ArgList {
	return al.Add("echo", v)
}

// --- TextSrc ---

func (al *ArgList) DataCompression(v int) *ArgList {
	return al.Add("dataCompression", v)
}

func (al *ArgList) PieceSize(v int) *ArgList {
	return al.Add("pieceSize", v)
}

func (al *ArgList) Type(v int) *ArgList {
	return al.Add("type", v)
}

func (al *ArgList) UseStringInPlace(v int) *ArgList {
	return al.Add("useStringInPlace", v)
}

// --- Tip ---

func (al *ArgList) Timeout(v int) *ArgList {
	return al.Add("timeout", v)
}

func (al *ArgList) Tip(v string) *ArgList {
	return al.AddString("tip", v)
}

// --- Toggle ---

func (al *ArgList) State(v bool) *ArgList {
	return al.AddBool("state", v)
}

func (al *ArgList) RadioGroup(v Widget) *ArgList {
	return al.AddWidget("radioGroup", v)
}

func (al *ArgList) RadioData(v int) *ArgList {
	return al.Add("radioData", v)
}

func (al *ArgList) ToggleShape(v int) *ArgList {
	return al.Add("toggleShape", v)
}

// --- Tree ---

func (al *ArgList) AutoReconfigure(v int) *ArgList {
	return al.Add("autoReconfigure", v)
}

func (al *ArgList) TreeForeground(v int) *ArgList {
	return al.Add("treeForeground", v)
}

func (al *ArgList) TreeParent(v Widget) *ArgList {
	return al.AddWidget("treeParent", v)
}

func (al *ArgList) Gravity(v int) *ArgList {
	return al.Add("gravity", v)
}
